### ISSUE TITLE
Would it be possible to add tab support?

### ISSUE THREAD

**Issue by chenoweth** [christoomey/vim-tmux-navigator#101]
Currently, if we have two tabs, and we are in the left one, hitting `<C-l>` doesn't move the focus to the next tab. It stays in the current tab / window. So to move between windows, we can use `<C-hjkl>` but between tabs we must use `gt` or `gT`.  
Would it be possible for the plugin to detect whether there's a tab next to the current one, so that we can continue to use the same mappings to move across windows and tabs?

**Comment by christoomey** [comment]
Hi @chenoweth, thanks for posting this. Unfortunately I think this is a bit too complicated for me to feel comfortable taking it on. We already have to jump through a bunch of hoops to get window <-> pane navigation working, and adding tabs would just add too many possibilities and branches to the code. I'm going to close this now, but feel free to reply or reopen if you think I missed something or have additional questions.

**Comment by chenoweth** [comment]
I understand, thank you very much for this very useful plugin and for taking the time to answer my question.
