### ISSUE TITLE
:source ~/.vimrc breaks connection with tmux

### ISSUE THREAD

**Issue by nitsky** [christoomey/vim-tmux-navigator#103]
When I re-load my vimrc with :source ~/.vimrc, I can still switch between vim panes, but I can no longer move to tmux panes. There must be something in this script that breaks when re-run. Restarting vim fixes the issue. Any ideas?

**Comment by christoomey** [comment]
Hey @nitsky, my guess is that there is an order of operations thing happing and that you have an old set of mappings hiding around. You can ask Vim for the current binding for a giving key mapping, as well as where it was set. For example, if I run `:verbose nmap <C-j>`, I get the following:

    n  <NL>        * :TmuxNavigateDown<CR>
            Last set from ~/code/vim/tmux-navigator/plugin/tmux_navigator.vim

Can you try the following to confirm:

1. Open a new Vim instance
2. Run `:verbose nmap <C-j>` and note the answer (should reference the plugin)
3. Re-source you `~/.vimrc`
4. Re-run `:verbose nmap <C-j>` and compare the answer

My guess is on the second check you'll see the mapping no longer reference the plugin, but instead a mapping like `<C-w>j` set in your Vimrc.

If that is true, then you just need to find the left over mappings and delete them from your Vimrc. If not, please let me know the output of the above commands and we can figure something out.

**Comment by nitsky** [comment]
Wow, you're right, I had some old C-{h,j,k,l} mapping in my vimrc, removing it fixed the problem. Thanks! :) :100:
