### ISSUE TITLE
The plugin stops working if editor is left idle for a few days

### ISSUE THREAD

**Issue by dorserg** [christoomey/vim-tmux-navigator#105]
I often hit the following problem when I leave an instance of vim open but inactive for a few days in one of my tmux tabs and then return back to it and try to navigate to a sibling pane (e.g. with `<Ctrl-j>`):

```
Error detected while processing function <SNR>23_TmuxWinCmd..<SNR>23_TmuxAwareNavigate..<SNR>23_TmuxCommand..<SNR>23_TmuxOrTmateExecutable..<SNR>23_StrippedSystemCall:
line    1: 
E484: Can't open file /tmp/vmyH93K/29
Error detected while processing function <SNR>23_TmuxWinCmd..<SNR>23_TmuxAwareNavigate..<SNR>23_TmuxCommand:
line    2:
E484: Can't open file /tmp/vmyH93K/30
Press ENTER or type command to continue
```

Looks like the plugin opens some temporary files which are then removed from underneath it if the editor is left inactive for some period of time.

My Vim version is 7.4, OS is Linux, the version of vim-tmux-navigator is latest (i.e. recently pulled from github via Vundle).

**Comment by christoomey** [comment]
Hi @dorserg, the temp file listed above is a tmux socket (I'm guessing). The plugin itself doesn't open any files. I'm guessing your tmux session / server got out of sync and the plugin hit that. We don't cache any values either so I'm guessing this is not the plugin directly, but not sure exactly why you hit this.

**Comment by dorserg** [comment]
Thanks for the prompt answer!

So you're guessing this happens when the tmux itself gets out of sync with the server -- in which case all of the open tmux tabs / vim instances in them would be affected, right? However what I observe is, when I'm actively working in one tab but leave another tab idle for, say, two days, vim instance in the "active" tab keeps working completely fine, but an instance in the "idle" tab experiences the problem. It's true, however, that if I don't connect to the server _at all_ for two days, all of the tabs get affected. Note also that if I exit vim and try to navigate between panes via tmux itself, everything works fine.

I'd be happy to help you debug this problem further. Does the plugin have any knobs I could turn to, say, produce more verbose logging? Any other pointers to help investigate?

Re failed sockets: does the plugin check whether a socket is valid or broken before using it? If it doesn't, can we add checks/retries/debug logging?

**Comment by dorserg** [comment]
After some digging I think I have found the root cause. The tmux socket file format, `/tmp/tmux-.../default`, didn't match the format of the files from my logs. Also, looking at the plugin source code, we failed even prior to parsing/using the socket, somewhere inside a simple `system(...)` command. 

It turns out `system` command requires access to a temporary directory (which I guess Vim creates on startup), and if that directory is removed (as is the case on my server where a periodic cron job cleans up stale `/tmp` files), any `system` call will fail. The design that 
- requires access to a tmp directory in case of even very simple "echo-only" commands and
- relies on that tmp directory always being present and doesn't try to recreate a new one in case of failure

is quite surprising if you ask me, but that's the way it is. So my workaround is to let Vim use a tmp dir that is not affected by periodic cleanups, e.g. `let $TMPDIR = $HOME."/tmp"`.

**Comment by christoomey** [comment]
Thanks for looking into this, and for sharing a solution.
