### ISSUE TITLE
Make bindings works when git diff tool is set to vimdiff

### ISSUE THREAD

**Issue by skgbanga** [christoomey/vim-tmux-navigator#107]
When git's diff tool is set to vimdiff, "TmuxPaneCurrentCommand" returns git and hence the bindings to switch between the panes don't work.
Is there a way to fix this?

**Comment by christoomey** [comment]
Hello @skgbanga, this is a known limitation and unfortunately there is no complete solution currently. https://github.com/christoomey/vim-tmux-navigator/pull/37 is one potential solution to this problem, and https://github.com/christoomey/vim-tmux-navigator/issues/96 captures my current best hope of solving this in a more complete way, but neither is quite ready for the prime time.

Closing this now as I believe it is covered by the existing PR & issue listed above, but please feel free to comment or reopen if you think I missed something.

**Comment by skgbanga** [comment]
Thanks Chris for the quick reply. 
For the time being, I have [fugitive](https://github.com/tpope/vim-fugitive) plugin installed, and use its :Gdiff command. Bindings obviously work in this.
