### ISSUE TITLE
Vim in remote session?

### ISSUE THREAD

**Issue by james64** [christoomey/vim-tmux-navigator#113]
Hey, I set up vim-tmux-navigator and sadly it's not working. My guess is that it's because of I run vim on remote computer through ssh. Thus this echo "#{pane_current_command}" will output ssh rather then vim. I haven't tested it yet (not having my laptop with me now) but it looks like a save bet.

Do you think there is any chance of vim-tmux-navigator working somehow even in this scenario? I'd love to!

thanks

**Comment by christoomey** [comment]
Hey @james64, unfortunately I don't think it would be possible. The outer tmux layer might work, but when navigating out of Vim, I think you'd hit a wall. Vim needs to be able to communicate back to tmux, which it would not be able to do from within the SSH session. Sorry to have to report that.

I'm going to close this now as I don't think there is much we can do, but feel free to comment or reopen if you think I missed something.

**Comment by james64** [comment]
This is a sad day for me but I expected something like this so no worries. Thank you for your reaction.

**Comment by KentVu** [comment]
vim likes to set xterm title to something like `[filename] (pwd) - VIM`. Should using `find-window` command help in this case, I've succeed finding VIM with: `findw VIM`.
