### ISSUE TITLE
Create a mapping to cycle tabs

### ISSUE THREAD

**Issue by himat** [christoomey/vim-tmux-navigator#116]
Is it possible to create a mapping to switch to the next tab in a sequence?
I'm asking because it's annoying to press c-h or c-l to go left or right, and j and k are more accessible, so I just want to map c-j to go to the next possible tab, but only the most recent tab command is provided.

So if I have 3 tabs open, 1 on top left, 1 on bottom left, 1 on entire right, and I'm currently in top left, pressing c-j would go to top bottom, and then pressing it again would go to entire right, and then pressing it again would go to top left.

**Comment by christoomey** [comment]
Hey @himat, I'm not sure I understand your question entirely. Vim has a concept of tabs (or "tab pages" as Vim documentation calls them), but you refer to them being to the left or right. Tab pages each fill the full Vim instance window and as such are not to the left or right. Maybe you're talking about the tabs in the tab bar? If so, Vim actually has built in mappings for cycling between tabs. `gt` will go to next tab, and `gT` will go to previous tab. No need to map anything. Also, there are commands `:tabnext` and `:tabprevious` which you can use if you want to map them.

My guess is I'm missing something here, so please do clarify if I am, but if not, hopefully the above helps.

**Comment by himat** [comment]
@christoomey Sorry, I called the different panes/splits as tabs for some reason, so just replace all instances of tab earlier with split. But I meant if I have two vim splits open and a tmux split all on the same screen for example then I would just want to cycle to the next one.

**Comment by stefanlendl** [comment]
+1

**Comment by linosgian** [comment]
+1

**Comment by christoomey** [comment]
Hey @himat, thanks for clarifying. Unfortunately I think what you're describing is best captured in https://github.com/christoomey/vim-tmux-navigator/issues/70, which we've recently decided to close out of lack of interest / no progress on implementation. At this point I'm pretty happy with the core functionality of this plugin and I don't consider the lack of this functionality a major limitation, so I'm going to close this issue based on that thinking.

**Comment by kiwiz** [comment]
Hi there, apologies for reviving this thread. Would you be interested in a PR for this functionality?

**Comment by himat** [comment]
I would still be interested in a PR for this.

**Comment by kiwiz** [comment]
@himat Apologies, upon a closer read of this issue, I think my request is actually about #70. @christoomey how do you feel about either of these tickets?
