### ISSUE TITLE
Can't use <C-h> to switch to NERDtree in Neovim

### ISSUE THREAD

**Issue by jrunning** [christoomey/vim-tmux-navigator#121]
When NERDtree is open I can switch *out* of the NERDtree pane by pressing `<C-l>` but I can't switch back *into* the NERDtree pane with `<C-h>`. I have to use `<C-w>h`.

I'm using the latest version of vim-tmux-navigator and have the latest code from the README in my `.tmux.conf`. I'm using tmux 2.2 and Neovim 0.1.3.

Any ideas?

**Comment by blueyed** [comment]
But other windows work fine?

**Comment by jrunning** [comment]
Oy. No, NERDtree was a red herring. `<C-h>` doesn't work at all in a Neovim window. It behaves just like `h` (moves one character to the left). I checked `:map` and don't see any conflicts. `:map <C-h>` returns the following:

```viml
n  <C-H>       * :TmuxNavigateLeft<CR>
```

It works as expected in tmux windows that aren't running Neovim.

**Comment by jagtesh** [comment]
I can confirm this issue. Happens only in neovim, regular vim works fine. Something to note, when I hit <C-h>, the bottom status line displays :noh.

**Comment by christoomey** [comment]
I believe this is purely a neovim issue, not something specific to this plugin. https://github.com/christoomey/vim-tmux-navigator/issues/71 covers it in detail, with our final resolution being https://github.com/christoomey/vim-tmux-navigator/issues/71#issuecomment-202422963.

@geoffharcourt quick ping on closing out that issue and adding something to the readme while we wait for neovim to fix itself, when you get a minute?

I'm going to close this issue as I believe https://github.com/christoomey/vim-tmux-navigator/issues/71 better covers it, and unfortunately there is not much we can do from the plugin itself. Please feel free to comment or reopen if there is something I missed.

**Comment by jrunning** [comment]
Thanks for your reply and sorry for duplicating the previous issue!

**Comment by christoomey** [comment]
No worries! Keep an eye on the other issue as we'll likely track the broader neovim issue there.
