### ISSUE TITLE
Commit to simplify Tmux mapping causing strange behavior

### ISSUE THREAD

**Issue by perks** [christoomey/vim-tmux-navigator#124]
Commit here [f5fcf](https://github.com/christoomey/vim-tmux-navigator/commit/f5fcf2afb5be7332484969c63e5ddee3483fd3f4)

Before update:
```vim
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <M-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <M-j> :TmuxNavigateDown<cr>
nnoremap <silent> <M-k> :TmuxNavigateUp<cr>
nnoremap <silent> <M-l> :TmuxNavigateRight<cr>
nnoremap <silent> <M-\> :TmuxNavigatePrevious<cr>
```

Had proper behaviour, was able to keybind `<C-J>` and `<C-K>` to other commands.

Now `<C-J>` and `<C-K>` cause the cursor to jump to adjacent Tmux panes from Vim, even though they are unbound.

Don't see any reason why this would be the case though, it doesn't make any sense, but reverting manually that one line back and forth reliably reproduces this behavior.

**Comment by blueyed** [comment]
Thanks for the report, fixed it.
