### ISSUE TITLE
Navigating `fzf.vim` broken since `tnoremap` update

### ISSUE THREAD

**Issue by alexlafroscia** [christoomey/vim-tmux-navigator#128]
The [latest commit](https://github.com/christoomey/vim-tmux-navigator/commit/e13914d89e9413cfa449f0c3daff18691356f2d1) broke the ability to use `ctrl-j` and `ctl-k` to navigate up and down in a list in `fzf.vim` when using Neovim.  I know that a cross-plugin compatibility issue is not really your problem, but it would be great to have this feature restored.  For the time being, I had to pin my `vim-plug` dependency to the previous commit to keep things working the way I'm used to.

Since detecting when `fzf.vim` is open, it might be nice to just add a configuration option that can be turned off to prevent the terminal remaps from being set.

**Comment by blueyed** [comment]
Yeah, sorry.

We should probably revert this altogether, and not add these mappings for terminal windows (which fzf uses).

**Comment by adamyonk** [comment]
I'm still seeing this issue on the latest commit. Is there some workaround to have it ignore J/K if you have the :Files pane open from FZF?

**Comment by blueyed** [comment]
@adamyonk 
Cannot reproduce: `<c-j>`/`<c-k>` is used by FZF for me (both Neovim and Vim).
I think you would have to open a new issue and provide more information.

**Comment by uzxmx** [comment]
I think `fzf.vim` also supports using `<c-p>`/`<c-n>` to navigate up/down, which is a same shortcut as navigating through shell history in a shell. The `p(revious)` and `n(ext)` is easier to remember than  `k`, `j` when navigating in a list (Still `hjkl` is definitely the best choice for left/up/down/right when moving the cursor in the editor). So I prefer `<c-p>`/`<c-n>` in this situation.

So if most people can accept using `<c-p>`/`<c-n>`, then we can add these mappings back for terminal windows.

Or how about this? Add a switch to let the user enable these mappings if they want to navigate when using terminal in nvim.
