### ISSUE TITLE
Invalid arguments for function <SNR>27_TmuxWinCmd

### ISSUE THREAD

**Issue by Jumblemuddle** [christoomey/vim-tmux-navigator#131]

**Comment by blueyed** [comment]
Please provide more context and the whole output from `:mess`.

**Comment by Jumblemuddle** [comment]
Installed in vim using Vundle.
Added default tmux entries as instructed.
Split tmux and attempted to C-j to split.
I can C-k from a shell to vim, but not the other way around.

:mess output
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"help.txt" [readonly] 223L, 8320C
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
E116: Invalid arguments for function <SNR>59_TmuxWinCmd
```

**Comment by Jumblemuddle** [comment]
Tried commenting out everything in vimrc (except this plugin and vundle stuff), no cigar.

**Comment by Jumblemuddle** [comment]
Calling :TmuxNavigateDown causes the same error.

**Comment by blueyed** [comment]
Can you call "debug TmuxNavigateDown" and find out what the args are?
Use "s" to step into a function/call, "n" for next and "echo too" to output var too.

**Comment by Jumblemuddle** [comment]
After pressing 's'
`cmd: call <80><fd>Q60_TmuxWinCmd('j')`
from this point, calling 's' or 'n' results in
`E116: Invalid arguments for function <SNR>60_TmuxWinCmd`

`echo too` doesn't work at any point in this chain.

**Comment by blueyed** [comment]
Sorry, I've meant `echo foo`, where foo is some variable.

It's a very strange issue, since it should be `function! s:TmuxWinCmd(direction)`, and `'j'` is a valid argument in that case..

There is not specific information with `:h E116`.
Maybe it's a bug in your Vim or Neovim version?!

**Comment by Jumblemuddle** [comment]
I've been messing with it a bit. Still no luck.
Vim version 7.4.1585

**Comment by Jumblemuddle** [comment]
Switching <SID> for s: seems to have fixed it.
If I understand correctly, that might not always work due to the function not being called in the context of the script? I have little to no experience with vimL.

**Comment by blueyed** [comment]
Oh, seems to be this issue: https://github.com/christoomey/vim-tmux-navigator/issues/110
While it's fixed in a later Vim, we have a PR waiting for that already, I'll merge it.
