### ISSUE TITLE
Autosave error when file not named

### ISSUE THREAD

**Issue by paymog** [christoomey/vim-tmux-navigator#142]
If autosave is turned on with `let g:tmux_navigator_save_on_switch = 1` and a vim instance in opened, ie running just `vim` and not `vim <path-to-file>` then navigating away from the tmux pane containing this unnamed (for lack of a better word) vim instance results in the following error:

```
Error detected while processing function <SNR58_TmuxWinCmd..<SNR>58_TmuxAwareNavigate:
line 11:
E32: No file name
```

Here's a [screenshot](https://cloud.githubusercontent.com/assets/1986950/17531318/2f1b321c-5e30-11e6-9e23-7300de4c0dcc.png) of the error.

EDIT: fix formatting

**Comment by blueyed** [comment]
Thanks for the report.
That might be easy to fix by just catching this Vim error there, i.e. nothing will be saved, but you won't see an error.

**Comment by paymog** [comment]
That'd be awesome :)

Hope it's easy to repro this issue.

**Comment by blueyed** [comment]
..and depending on the code afterwards, this should be skipped maybe.

**Comment by paymog** [comment]
All I needed was a hint ;)

I've literally never written vimscript. Hopefully I'll get a PR out for this later today/early tomorrow.
