### ISSUE TITLE
Bindings aren't working

### ISSUE THREAD

**Issue by mtfurlan** [christoomey/vim-tmux-navigator#146]
Greetings. I'm on mint 18, vim 7.4.1689, tmux 2.1.

`:TmuxCurrentPaneCommand` returns `vim`
`:TmuxNavigateDown` or up navigates fine.
So it's something with the bindings.

I put 

```
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft
nnoremap <silent> <c-j> :TmuxNavigateDown
nnoremap <silent> <c-k> :TmuxNavigateUp
nnoremap <silent> <c-l> :TmuxNavigateRight
nnoremap <silent> <c-\> :TmuxNavigatePrevious
```
and 
```
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-\> :TmuxNavigatePrevious<cr>
```
(Does that matter? Seems like an error to me, but it's what the README and the plugin says...)

Output of `run-shell "ps -o state= -o comm= -t $(tmux display -p '#{pane_tty}') > tmux-debug.txt"`: [tmux-debug.txt](https://github.com/christoomey/vim-tmux-navigator/files/415345/tmux-debug.txt)

**Comment by mtfurlan** [comment]
Okay, it's actually bind isn't working, not binds, I just didn't test very well. All directions work except for down.
My [.vimrc](https://github.com/mtfurlan/dotfiles/blob/master/link/.vimrc) is almost identical to this, I just switched from Pathogen to Vagrant.

**Comment by blueyed** [comment]
> I just switched from Pathogen to Vagrant

Huh?  Vagrant?

What does `:verbose map <c-j>` say?

**Comment by mtfurlan** [comment]
...I meant Vundle. Sorry.
```
v  <NL>          <Plug>IMAP_JumpForward
        Last set from ~/.dotfiles/link/.vim/bundle/vim-latex/plugin/imaps.vim
n  <NL>          <Plug>IMAP_JumpForward
        Last set from ~/.dotfiles/link/.vim/bundle/vim-latex/plugin/imaps.vim
```
So it's obviously bound by vim-latex, but I don't know enough to fix it, would you mind explain

**Comment by blueyed** [comment]
vim-latex apparently overwrites the mapping.
You would need to change the order of plugins being loaded or find an option in vim-latex to not override it.
Another option would be to override it yourself to what vim-tmux-navigator sets it to.

Closing this issue for now, since it's not a problem with v-t-n.

**Comment by mtfurlan** [comment]
Yeah sorry.

If you're willing to help me fix this anyway:
I moved vim-tmux-navagator to last in the Vundle list, and I (still) have
```
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-\> :TmuxNavigatePrevious<cr>
```
in my vimrc, but still no change. (Is the `<cr>` important?)

How do I approach debugging this?

**Comment by blueyed** [comment]
Yes, the `<cr>` is important - without it you would end up with the `:TmuxNavigateLeft` in the cmd window.

Check out vim-latex's documentation if you can configure it to not override/set mappings.

But I would assume that `nnoremap <silent> <c-j> :TmuxNavigateDown<cr>` in your vimrc would override it?!

**Comment by blueyed** [comment]
> How do I approach debugging this?

Start from disabling vim-latex.

**Comment by mtfurlan** [comment]
Shockingly enough, that fixes it.

So how do I actually go about resolving this conflict? I would have thought
the bindings at the end of my vimrc would override it, yeah.

https://github.com/vim-latex/vim-latex is the relevant repository if you're
willing to test.

Thanks for the help.

**Comment by blueyed** [comment]
You have to manually create (different) mappings for vim-latex' imap plugin: http://stackoverflow.com/a/34811407/15690.
I would also create an issue for the vim-latex plugin to have some functionality to disable this part of the plugin altogether (given that there are multiple similar issues on StackOverflow already).

**Comment by mtfurlan** [comment]
Yeah, that completely fixed it.
Many thanks.
I'll go open an issue there.
Cheers!
