### ISSUE TITLE
Is there yet another awesome way to bind shortcut?

### ISSUE THREAD

**Issue by z1003031335** [christoomey/vim-tmux-navigator#149]
I have using C-k and C-h for editing in terminal,now vim-tmux-navigator had changed shortcuts  to navigate window, i can't bear it.

**Comment by christoomey** [comment]
There is [a section in README on customizing the keybindings](https://github.com/christoomey/vim-tmux-navigator#custom-key-bindings). **Note**, you'll need to configure the Vim plugin _and_ update the tmux key bindings.

**Comment by blueyed** [comment]
@z1003031335 
What do you use instead?

I can see that the defaults are probably not optimal, and that e.g. Alt-hjkl might be better.

**Comment by z1003031335** [comment]
@blueyed i have no idea for this,now i don't use this plugin bascially because C-h and C-k are pretty practical to me in terminal.

**Comment by blueyed** [comment]
@z1003031335 
Ok, let us know when you come up with something.. :)
