### ISSUE TITLE
Cannot <C-h> from vim (either to vim or to tmux) when TERM is tmux-256color

### ISSUE THREAD

**Issue by RatanRSur** [christoomey/vim-tmux-navigator#155]
I have tmux-256 color set up so I can have italics but it breaks this :(

**Comment by christoomey** [comment]
Hey @RatanRSur, sorry for the delayed response here! Can you confirm if you've tried the [neovim `<C-h>` fix](https://github.com/christoomey/vim-tmux-navigator#it-doesnt-work-in-neovim-specifically-c-h) in the readme?

Beyond that, I don't know if there is anything we can do. I personally run with `screen-256color` as my `default-terminal` setting, and assuming we can't resolve this, we may just need to add a note making that explicit.
