### ISSUE TITLE
Cannot navigate out of vim after reloading .vimrc

### ISSUE THREAD

**Issue by samcal** [christoomey/vim-tmux-navigator#157]
If I am editing my .vimrc, after applying changes with `:so $MYVIMRC`, I am no longer able to use \<c-h,j,k,l\> to navigate to another tmux pane. Everything is completely normal before reloading the configuration. My dotfiles are [here](https://github.com/samcal/dotfiles).

**Comment by blueyed** [comment]
Check `:verb map <c-j>` before and after.

Very likely related to your setup.

**Comment by samcal** [comment]
Yep, of course!

I forgot to remove my old mappings for moving between vim splits. Thanks!
