### ISSUE TITLE
tmux navigation with vim open not working 

### ISSUE THREAD

**Issue by nrupatunga** [christoomey/vim-tmux-navigator#158]
Hi @blueyed @christoomey 

I have been trying to make vim-tmux-navigator work with tmux. 

I have been trying to debug but without no success . Will you be able to point me where I am doing it wrong. 

> Vim version - 7.4
> tmux version - 2.4
> OS - Ubuntu 14.04

Here is my setting in .tmux.conf file. 
```

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-capture-pane-contents 'on'

bind Space choose-buffer
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'
```

I did make sure that there are no mappings in `.vimrc `as well, with search pattern

>  \vn(nore)?map\s+\<c-[hjkl]\>

Output for `:TmuxPaneCurrentCommand` gives the following error

> Error detected while processing function <SNR>47_TmuxPaneCurrentCommand[1]..<SNR>47_TmuxCommand[1]..<SNR>47_TmuxSocket:
> line    2:
> E684: list index out of range: 0
> E15: Invalid expression: split($TMUX, ',')[0]
> error connecting to 0 (No such file or directory)

Your help is much appreciated. 

Thanks

**Comment by christoomey** [comment]
Hello, sorry to hear about the troubles. A few questions / comments that may help:

1. Can you give any more detail around "doesn't work?" Does navigation never happen? Only in Vim? Only in touch?
2. You have the key bindings and the tmux plugin both active in your tmux conf. You'll only want one or the other as they do the same thing.
3. `TmuxPaneCurrentCommand` is no longer relevant (sorry for out of date docs, I'll make sure to update) but the error is still interesting. Can you confirm the output of `verbose nmap <-j>` and what happens if you run the command `TmuxNavigateDown`?

**Comment by nrupatunga** [comment]
Thank you @christoomey  for quick reply. 

1. Navigation to other panes doesn't happen when i have opened Vim. Otherwise navigation works as expected. 

2. I removed tmux plugin settings in tmux conf as below shown

```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-capture-pane-contents 'on'

bind Space choose-buffer
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

```

3.  `verbose nmap <-j> `  says `no mapping found` and `TmuxNavigateDown` outputs nothing.

**Comment by christoomey** [comment]
@nrupatunga Do you have the vim plugin installed? This setup requires configuration in both tmux & Vim, and based on your last line it looks like the Vim plugin is not active, although I would expect `: TmuxNavigateDown` to error if the plugin were actually not installed. Can you confirm the Vim configuration you have in place re: this plugin?

**Comment by nrupatunga** [comment]
@christoomey sorry for late reply.

I have installed the vim-tmux-navigator plugin. I verified this with the command `:scriptnames ` inside vim. 
It shows that vim-tmux-navigator plugin is loaded 

```
 45: ~/.vim/plugged/Align/plugin/AlignPlugin.vim
 46: ~/.vim/plugged/Align/plugin/cecutil.vim
 47: ~/.vim/plugged/vim-tmux-navigator/plugin/tmux_navigator.vim
```

On the other machine at home,   `verbose nmap <-j> `  says `no mapping found` and `TmuxNavigateDown` outputs nothing. I am having hard time debugging. Any pointers? 

Let me know if you need more information.

**Comment by blueyed** [comment]
It should be `verbose nmap <c-j>`.

**Comment by nrupatunga** [comment]
Hi @blueyed / @christoomey 

Here is the output of `verbose nmap <c-j>` in vim

```
n  <NL>        * :TmuxNavigateDown<CR>
        Last set from ~/.vim/plugged/vim-tmux-navigator/plugin/tmux_navigator.vim
```

**Comment by nrupatunga** [comment]
@christoomey /@blueyed 

This issue is happening in tmux-2.4, I am not sure whether the problem is due to tmux or vim plugin. I hope it will get fixed either way.

Thank you.

**Comment by hk0i** [comment]
`:verbose nmap <c-j>` helped me discover that my config has been broken for years and any time I source my keymap vimrc it was clobbering the tmux navigate mappings.

I've now removed those mappings, I'm going to see if that helps me.

Hope that helps anyone else who got here from Google.
