### ISSUE TITLE
<C-h> is not working both in vim and tmux.

### ISSUE THREAD

**Issue by wizzup** [christoomey/vim-tmux-navigator#162]
`<C-h>` in vim is move cursor back (like `<h>`).
`<C-h>` in tmux do nothing.
`<C-l>` do jump horizontal between tmux's pane

`<C-w><C-h>` and `:TmuxNavigateLeft`  is still work in vim for jump to left split

`:TmuxNavigateLeft` also jump out of vim to left tmux' pane.

The system is Arch linux, xterm 327, neovim 0.1.7 and tmux 2.3

This is my $MYVIMRC

	call plug#begin()

	"" vimplug manage vimplug
	Plug 'junegunn/vim-plug'

	"" tmux pane / vim split using same key combination
	Plug 'christoomey/vim-tmux-navigator'

	call plug#end()

and mapping (from command `:map`) , noted that `<C-J>` is missing, I have no idea why

    n  <C-H>       * :TmuxNavigateLeft<CR>
    n  <NL>        * :TmuxNavigateDown<CR>
    n  <C-K>       * :TmuxNavigateUp<CR>
    n  <C-L>       * :TmuxNavigateRight<CR>
    n  <C-\>       * :TmuxNavigatePrevious<CR>

and  tmux.conf

	# Smart pane switching with awareness of Vim splits.
	# See: https://github.com/christoomey/vim-tmux-navigator
	is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
	    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
	bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
	bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
	bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
	bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
	bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

**Comment by wizzup** [comment]
just found that this is already know nvim [issue](https://github.com/christoomey/vim-tmux-navigator#it-doesnt-work-in-neovim-specifically-c-h), closed

**Comment by sajaysurya** [comment]
I had the same problem while using vim and tmux in xterm. Turns out xterm translates `<c-h>` into backspace. I had to add `XTerm*ptyInitialErase: true` in `.Xresources` to get `<c-h>` working.

**Comment by jsrozner** [comment]
> just found that this is already know nvim [issue](https://github.com/christoomey/vim-tmux-navigator#it-doesnt-work-in-neovim-specifically-c-h), closed

@wizzup 
How did you resolve?
