### ISSUE TITLE
Making vim-tmux-navigator work with two keys

### ISSUE THREAD

**Issue by hgiesel** [christoomey/vim-tmux-navigator#168]
My vimrc
```
""" christoomey/vim-tmux-navigator
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <c-\>h :TmuxNavigateLeft<cr>
nnoremap <silent> <c-\>j :TmuxNavigateDown<cr>
nnoremap <silent> <c-\>k :TmuxNavigateUp<cr>
nnoremap <silent> <c-\>l :TmuxNavigateRight<cr>
nnoremap <silent> <c-\><bslash> :TmuxNavigatePrevious<cr>
nnoremap <silent> <c-\><c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-\><c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-\><c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-\><c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-\><c-\> :TmuxNavigatePrevious<cr>
```

My tmux.config
```
# Moving around smart pane switching with awareness of vim splits {{{
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key \ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
# }}}
```

These are my settings. The problem is that inside `vim`, the first `<c-\>` is swallowed by `tmux`, and the next `<c-/><c-l>` will trigger the command.

So all in all, I need to enter `<c-\><c-\><c-h>` in `vim` and `<c-\><c-h>` in `tmux`. Is there some workaround?

**Comment by markstos** [comment]
The problem appears to be that your setting don't match. It appears that your `.tmux.conf` file is is set to to respond to either "<prefix> h"  or  "<prefix> C-h" to navigate left. If vim is detected, it will send "C-h" to Vim. But your .vimrc isn't configured to respond to "C-h" for navigation, it's set to respond to "<C-\>h".

**Comment by christoomey** [comment]
Hi @hgiesel, I agree with @markstos's assessment (thanks Mark!) that your configurations don't line up across tmux & vim, and that that is the likely source of your difficulty. I'm going to close this now as I think this is a question of configuration rather than an issue with the plugin, but please feel free to comment or re-open if you think there is actually something wrong in the plugin.
