### ISSUE TITLE
:TmuxPaneCurrentCommand returns failed to connect to server: No such file or directory

### ISSUE THREAD

**Issue by raghuramos1987** [christoomey/vim-tmux-navigator#169]
Mac OSX 10.11.6
VIM - Vi IMproved 8.0
$tmux -V
tmux 2.0

**Comment by christoomey** [comment]
Apologies, that command is a bit out of date. I hope to update soon, but in the mean time, is there another error that you encountered that lead you to run `: TmuxPaneCurrentCommand` (which is a debug command)? Perhaps I can help with that.

**Comment by raghuramos1987** [comment]
I am unable to switch between tmux panes when I'm inside vim. This used to work with an older version of the plugin (unfortunately I dont know which version) and stopped working when I ran plugin update from vundle. How can I debug this? Switching panes works when I'm switching from a normal pane into a pane with vim.

**Comment by blueyed** [comment]
@raghuramos1987 
You could try to git-bisect it to some change in this plugin.  This might help to find out why it stopped working for you.

**Comment by raghuramos1987** [comment]
Very good idea. It looks like everything before this commit is working. 5d76881c6ee5de89994ef7e2308bb1ddaef38bea

I'm going to fix this for myself for now by rolling back to before that. Please let me know if I can help in debugging.

**Comment by christoomey** [comment]
Hey @raghuramos1987, sorry to hear about the trouble. The commit in question adds some logic around the tmux socket. Could you check the following:

From your shell, run

```sh
echo $TMUX
```

You should see a string like `/private/tmp/tmux-501/default,625,1`, where the socket is the part before the first comma, so `/private/tmp/tmux-501/default` in this case.

Assuming you see something similar, could you try grabbing that text and running the following command with the socket you found in the previous step inline?

``` sh
tmux -S /private/tmp/tmux-501/default split-window
```

The expected outcome will be the current tmux pane splitting.

**Comment by raghuramos1987** [comment]
Problem solved. I was setting $TMUX to override some other stuff. Moved that to use $TMUX_CMD and this works on the latest master. Thanks @christoomey !

**Comment by christoomey** [comment]
Glad to hear it, and thanks for debugging!
