### ISSUE TITLE
Running vim vsplit remotely in pane 1, pane 0 is host

### ISSUE THREAD

**Issue by andrewzigerelli** [christoomey/vim-tmux-navigator#173]
Hi,

Is this supported? Frequently, I need to code remotely but view files on my host. I hope to run a tmux (on host) with one pane with host code (with vim splits) and the other pane an ssh session with vim splits.

I can move between vsplits in the host pane, but not in the remote pane. The remote pane requires <C-w> direction, so as an example, it requires <C-wj> instead of just <C-j>

Is this best accomplished with conditional mappings? Or is my setup wrong?

**Comment by christoomey** [comment]
Unfortunately handing nested SSH sessions with the tmux / Vim combination is a bit out of the scope of what this plugin is intended to do. I expect it would be possible to make things work, but I rarely work in SSH and have not spent any time investigating, so I can't offer much more than that. Sorry I can't be of more help.
