### ISSUE TITLE
just to confirmed the behaviour

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [christoomey/vim-tmux-navigator#176]
with this plugin, we can jump from within a vim in a tmux pane to another tmux pane without tmux prefix, but, it can not jump reversely without prefix key, is it right?
now in my tmux, <c-j> and <c-k> will work without prefix, no matter there is vim launched, <c-h> and <c-l> does not work without prefix for vim.

**Comment by christoomey** [comment]
Hello @FinallyFinancialFreedom. To confirm, the intended functionality is for _non_prefixed key bindings to work in either vim or tmux. The plugin should know if you're in Vim or tmux, and even if you're at the edge of a Vim window, and do the correct thing. You should not need to use the tmux prefix before any key sequence to move.

Please see the [troubleshooting guide](https://github.com/christoomey/vim-tmux-navigator#troubleshooting) which hopefully can help you sort out your issue. I'm going to close this now as it is too generic for us to help with, but please feel free to re-open or comment if you end up trying the troubleshooting tips and are still having trouble.
