### ISSUE TITLE
Navigator doesn't recognize system editor symbolic link. (& fix)

### ISSUE THREAD

**Issue by stevefan** [christoomey/vim-tmux-navigator#186]
For Ubuntu 16.04

I found that only when I called vim as my system editor, the navigator keys wouldn't let me switch between vim splits.

After some investigating, I found that this was because the regex didn't catch that I was using the system editor.

My fix is to tac on |editor in the regex in `~/.tmux.conf`:

```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \  
    | grep -iqE '^[^TXZ ]+ +(\\S+\/)?g?(view|n?vim?x?|editor)(diff)?$'"
```

A note about this could be useful in the README.

A better solution would be to find out the actual bin, if symbolic linked to, though the ps call would be.

edits**
specified OS & file with the modified line

**Comment by blueyed** [comment]
So the bin is `editor` then?
How does it happen?  Is this a symlink somehow?  (as with Debian/Ubuntu)
Does it also reflect what you have in `$EDITOR`?

**Comment by stevefan** [comment]
This is for Ubuntu 16.04.
No $EDITOR variable.

It happens through update-alternatives.
`sudo update-alternatives --install /usr/bin/editor editor /path/to/vim 1`

**Comment by blueyed** [comment]
I see.
`/usr/bin/editor` is not a symlink though is it?
Anyway, I think the pattern should just match it, and also be more friendly to NixOS (https://github.com/christoomey/vim-tmux-navigator/pull/171).
@christoomey's call I guess.

I am still up for the fork mentioned in https://github.com/christoomey/vim-tmux-navigator/pull/170#issuecomment-287574987, but am happy enough with my own local version for now.

**Comment by christoomey** [comment]
Hi @stevefan, thanks for sharing and for the detailed writeup and proposed solution.

I try to be cautious with extending the match pattern as I think a false positive is possibly worse (you'd be stuck in tmux w/ the nav keys being sent through to the underlying process) than the current failure mode, and adding `|editor` feels like it could open the door to false positives.

I'm thinking a bit about how to strike the right balance between keeping the core super stable, while making it "just work" for as many configurations as possible. I'll keep this open for now while I think through the options, but as it stands I'm hopeful that the fix of updating the pattern in your `~/.tmux.conf` covers your needs.

**Comment by stevefan** [comment]
@blueyed Dug a little bit into the update-alternatives system, it uses symlinks.

```
host$ ll /usr/bin/ | grep editor
lrwxrwxrwx  1 root root          24 Jun 18 14:31 editor -> /etc/alternatives/editor*
...
host$ ll /etc/alternatives/ | grep editor
lrwxrwxrwx   1 root root    18 Nov  2 10:32 editor -> /usr/local/bin/vim*
...
```

**Comment by stevefan** [comment]
closing

**Comment by stevefan** [comment]
closing as solved
