### ISSUE TITLE
Does not work with neovim's :terminal

### ISSUE THREAD

**Issue by shiro** [christoomey/vim-tmux-navigator#187]
If you start a terminal inside of neovim (with `:terminal`) it becomes impossible to switch the pane. (both inside vim and tmux).
The funny part is: it does seem to work again after opening vim inside said terminal ^^

**Comment by christoomey** [comment]
I'm not a neovim user so I've not been able to test this myself, but [this PR adds bindings for neovim's terminal mode](https://github.com/christoomey/vim-tmux-navigator/pull/172). Can you check that out, and if it works for you let us know as a data point around that functionality?

**Comment by blueyed** [comment]
See https://github.com/christoomey/vim-tmux-navigator/pull/111 and https://github.com/christoomey/vim-tmux-navigator/pull/129 - i.e. we've tried it already.. ;)

**Comment by bangn** [comment]
I got same problem. Cannot navigate in neovim however it works with vim.

**Comment by damnskippy** [comment]
@bangn when you "it works with vim", are you saying it works with vim terminal?
The reason I'm asking is because this doesn't work for me and was wondering whether vim's terminal is supported or not.  Thanks.

**Comment by bangn** [comment]
Hi @damnskippy,

Im not fully understand what you meant by vim terminal. However, when I used vim, gtk-terminal and tmux, vim-tmux-navigator works for me. Neovim will not

Hope it helps

Cheers 
Bang

**Comment by damnskippy** [comment]
@bangn @christoomey 
No I was just wondering about something like this to navigate out of a native vim terminal.
```
if has('terminal')
    tmap <c-k> <c-w>:TmuxNavigateUp<cr>
    tmap <c-j> <c-w>:TmuxNavigateDown<cr>
    tmap <c-h> <c-w>:TmuxNavigateLeft<cr>
    tmap <c-l> <c-w>:TmuxNavigateRight<cr>
endif
```
I already have the above in my vimrc and works great, so I'm all set; but just wondering if it makes sense to integrate into this plugin "natively", but I also see how it is out of scope in some ways.

**Comment by christoomey** [comment]
I believe we've avoided adding (actually added and then subsequently removed) the mappings as part of the core plugin as they interfere with fzf.vim functionality (see https://github.com/christoomey/vim-tmux-navigator/issues/128).

**Comment by bangn** [comment]
Got it working by changing the regex. I think because I installed neovim via `nix` package manager.

Credit to: https://mendo.zone/fun/neovim-setup-haskell/

**Comment by christoomey** [comment]
Closing this in favor of https://github.com/christoomey/vim-tmux-navigator/pull/172 where I'd like to collect any conversations around terminal mode mappings.
