### ISSUE TITLE
compatibility with fzf

### ISSUE THREAD

**Issue by pruett** [christoomey/vim-tmux-navigator#188]
when opening up a [fzf](https://github.com/junegunn/fzf) window within a tmux session Ctrl-j/k (used for navigating up and down the fuzzy list) are mapped to `select-pane -D/-U`. Can someone help parse these lines from the docs? I'm hoping I can detect when i'm in the fuzzy finder and have my keybindings act as normal. 

```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
```

**Comment by pruett** [comment]
ah, this article solves the issue https://blog.bugsnag.com/tmux-and-vim/

**Comment by gfontenot** [comment]
I have an updated config that includes `fzf` in the pattern: https://github.com/gfontenot/dotfiles/blob/master/tmux.conf#L97-L104

**Comment by christoomey** [comment]
Oooh that's fancy @gfontenot. I like the variation on the pattern you've introduced there. I think I'll look into updating the default to follow that form. Thanks for sharing!

**Comment by mishagantz** [comment]
> I have an updated config that includes `fzf` in the pattern: https://github.com/gfontenot/dotfiles/blob/master/tmux.conf#L94-L104
> 
> --edit--
> 
> Fun fact: I thought I submitted this comment yesterday but I just hit preview. Sorry for the late response.

5 years later this helped me, thank you!

**Comment by jacobchrismarsh** [comment]
> 5 years later this helped me, thank you!

Same here, thanks @gfontenot!

**Comment by gfontenot** [comment]
I did notice that the link is out of date, so for posterity here's the config I'm (still) using:

```sh
# Smart pane switching with awareness of vim and fzf
forward_programs="view|n?vim?|fzf"

should_forward="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?($forward_programs)(diff)?$'"

bind -n C-h if-shell "$should_forward" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$should_forward" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$should_forward" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$should_forward" "send-keys C-l" "select-pane -R"
bind -n C-\\ if-shell "$should_forward" "send-keys C-\\" "select-pane -l"
```

**Comment by suvasanket** [comment]
> I did notice that the link is out of date, so for posterity here's the config I'm (still) using:
> 
> ```shell
> # Smart pane switching with awareness of vim and fzf
> forward_programs="view|n?vim?|fzf"
> 
> should_forward="ps -o state= -o comm= -t '#{pane_tty}' \
>   | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?($forward_programs)(diff)?$'"
> 
> bind -n C-h if-shell "$should_forward" "send-keys C-h" "select-pane -L"
> bind -n C-j if-shell "$should_forward" "send-keys C-j" "select-pane -D"
> bind -n C-k if-shell "$should_forward" "send-keys C-k" "select-pane -U"
> bind -n C-l if-shell "$should_forward" "send-keys C-l" "select-pane -R"
> bind -n C-\\ if-shell "$should_forward" "send-keys C-\\" "select-pane -l"
> ```

thanks man really helpful😇
