### ISSUE TITLE
Vim navigation doesn't work with tmux.gtk3

### ISSUE THREAD

**Issue by mahemoff** [christoomey/vim-tmux-navigator#191]
The plugin is working fine with the standard Vim 8.0 on Ubuntu 17.04, but installing vim-gnome package and running vim.gtk3, vim window navigation no longer works. (Can still navigate between tmux panes including from Vim.)

**Comment by mahemoff** [comment]
I fixed this by changing the recommended tmux.conf snippet to detect vim.gtk3:

> is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?x?|vim.gtk3)(diff)?$"'

Maybe the recommended config should support something like "vim(\.)?.*" (ie vim followed by optional suffix)

**Comment by christoomey** [comment]
Hey @mahemoff, thanks for sharing the fix here! Historically I've been more open to adding to the default grep pattern, but I've lately been opting for a more conservative approach leaning towards less changes to the plugin code itself.

That said, I'm going to take a note to myself to update the documentation to better clarify how anyone would go about updating the pattern to handle other vim command name variants.
