### ISSUE TITLE
feature request: embedded tmux support

### ISSUE THREAD

**Issue by DanielFGray** [christoomey/vim-tmux-navigator#20]
I don't know how possible this would be, but it'd be very cool to navigate panes that are also inside embedded tmux sessions.
I tried something like the following but of course it gets stuck once inside an ssh session
    `bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqP '(vim|ssh)' && tmux send-keys C-h) || tmux select-pane -L"`

**Comment by mabushey** [comment]
You can always use screen and run tmux inside of that...
