### ISSUE TITLE
Ignore certain Vim windows (e.g. quickfix)

### ISSUE THREAD

**Issue by blueyed** [christoomey/vim-tmux-navigator#204]
I think it would be a nice feature to allow for skipping/ignoring some Vim windows like quickfix/location lists, i.e. when navigating down and it would switch to a quickfix window in Vim, it would go back in Vim, but switch the tmux pane instead.

Code for this should go here then: https://github.com/christoomey/vim-tmux-navigator/blob/daae735fbb0fc10e51cfe0e9cba01de53c19417d/plugin/tmux_navigator.vim#L92.

What do you think?

My use case is that I usually am skipping over quickfix windows when using vim-tmux-navigator's mappings (i.e. have to use them twice).

**Comment by damnskippy** [comment]
OTOH, I like the consistency of being able to use the same mappings regardless of the window type or pane boundary - which I feel is the selling point of this plugin, including to switch to a quickfix window, for instance.  That said, I do see some value in being able to skip window types under certain circumstances.  I'd suggest such a feature if added be made optional and user configurable.

**Comment by christoomey** [comment]
Hi @blueyed, I've done a bit of thinking on this and I've concluded that I'd rather not support this distinction in the plugin proper. I personally rely on the navigation being consistent between all windows, including quickfix and others. I'm generally _very wary_ of adding any additional code paths or complexity to the core functions of the plugin, and this feels like something that would add a non-trivial amount of code.
