### ISSUE TITLE
vim-tmux-navigator doesnt switch upwards if the cursor is in `NerdTree` plugin

### ISSUE THREAD

**Issue by alphaCTzo7G** [christoomey/vim-tmux-navigator#205]
I use the `NerdTree` plugin which is very popular among vim users. If the cursor is located in the `NerdTree`  window, and you try to move upwards by using the `ctrl-j`, it just stays there.

However, if the cursor is in `NERDTree` pane and you try to do a `Ctrl-h/l`, it does work as expected.

Any idea why this is happening? Or if it can prevented?

**Comment by christoomey** [comment]
My guess is that `NERDTree` is setting buffer specific mappings on startup. You can run `:verbose nmap <C-j>` while in the NERDtree window to check. It will likely point to some NERDTree file.

Unfortunately there isn't a ton we can do from vim-tmux-navigator, but I'm guessing there is some configuration or event you can hook into to override the NERDtree behavior.

I'm going to close this now as I don't think there is anything to be done our our side, but please do comment if you're able to figure out a workaround, our reopen if you think I've missed something or that there actually is something in vim-tmux-navigator that needs to be addressed.

**Comment by jharwig** [comment]
For anyone interested, adding these to vimrc fixed it

```
let g:NERDTreeMapJumpPrevSibling=""
let g:NERDTreeMapJumpNextSibling=""
```

**Comment by alphaCTzo7G** [comment]
@jharwig.. thanks this works well now.. 

@christoomey .. Because NERDTree is pretty popular.. I am guessing maybe most people who use this plugin will probably also use NERDTree..

Perhaps.. this plugin could check if `NERDTree` is switched on in the current session. 
If so, set
```
let g:NERDTreeMapJumpPrevSibling=""
let g:NERDTreeMapJumpNextSibling=""
```
