### ISSUE TITLE
Error: TTY could not be found

### ISSUE THREAD

**Issue by weilbith** [christoomey/vim-tmux-navigator#206]
The plugin works fine in _Vim_ and from _Vim_ to _TMux_. But in _TMux_ is doesn't work. This seems to be caused by the definition of the `is_vim` variable. I tried this command manually and I get the following error by `ps`:
```zsh
error: TTY could not be found

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
```

Can you help me for this?

**Comment by christoomey** [comment]
Can you share the exact command you were running that caused this error? Also tmux & shell versions while you're at it?

In the mean time, you could revert back to the previous version of the `is_vim` check command, documented [here](https://github.com/christoomey/vim-tmux-navigator/tree/33d688a028cd9d5f3ab8a4d994dbe14b8e13e55e#tmux). 

``` tmux
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?x?)(diff)?$"'
```

It is slightly more naive than the current one using `ps`, but it should work in 95% of use cases and might help while we figure out the issue with the `ps` version.

**Comment by blueyed** [comment]
I think https://github.com/christoomey/vim-tmux-navigator/pull/201 would help here, too.

@weilbith 
Can you try it?
