### ISSUE TITLE
Please add terminal mode maps

### ISSUE THREAD

**Issue by Heithoff** [christoomey/vim-tmux-navigator#207]
Vim8.1 now has terminal mode.    If some maniac has Vim open in a tmux session and starts a Vim terminal window, then the normal mode mappings won't work from the terminal window.

This could be added to plugin/tmux_navigator.vim after the nnoremaps.
  if has('terminal')
      tnoremap <silent> <c-h> <c-w>:TmuxNavigateLeft<cr>
      tnoremap <silent> <c-j> <c-w>:TmuxNavigateDown<cr>
      tnoremap <silent> <c-k> <c-w>:TmuxNavigateUp<cr>
      tnoremap <silent> <c-l> <c-w>:TmuxNavigateRight<cr>
      tnoremap <silent> <c-\> <c-w>:TmuxNavigatePrevious<cr>
  endif

**Comment by christoomey** [comment]
Hi @Heithoff, we have a few open issues and a PR related to terminal mode mappings (I'm working right now to consolidate them). IIRC there are some potential issues or complications when running this with FZF so I'm weary of adding these. You certainly can add to your own vimrc, but for now I'm going to close this in favor of https://github.com/christoomey/vim-tmux-navigator/pull/172 where I'd like to collect any conversations around terminal mode mappings.
