### ISSUE TITLE
Disabling the control + hjkl movement on insert mode

### ISSUE THREAD

**Issue by YOnoda** [christoomey/vim-tmux-navigator#209]
Hi,

I use control + hjkl to move the cursor on vim on insert mode, but after installing this plugin, the cursor movement does no longer work, although now I can move to a different pane on normal mode.

I think the tmux movement key is incompatible with it but is it possible to make it only work on normal mode?

**Comment by christoomey** [comment]
Hi there, I’m surprised to hear you’re having this issue as we use `nnoremap` to map the movement keys, and as such they should not be active in insert mode, nor should installing this plugin have any effect on your insert mode key bindings.

To run a quick test, can you check the output of running the command `:verbose imap <C-j>`?

**Comment by YOnoda** [comment]
Hi, @christoomey 

Thanks for the response. Really sorry to say that the problem is caused by tmux, not your plugin...

**Comment by blueyed** [comment]
@YOnoda 
Please elaborate on what the issue with tmux is.

**Comment by YOnoda** [comment]
Hi,

Sorry again that the problem is that I use Dvorak, and I only changed the first part of the following keys to my Dvorak setting (e.g mine was `bind -n **C-d** if-shell "$is_vim" "send-keys **C-h**"  "select-pane -L"`). 

The following code does make the cursor move on the insert mode working fine.

```
bind -n C-d if-shell "$is_vim" "send-keys C-d"  "select-pane -L"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -D"
bind -n C-t if-shell "$is_vim" "send-keys C-t"  "select-pane -U"
bind -n C-n if-shell "$is_vim" "send-keys C-n"  "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind -T copy-mode-vi C-d select-pane -L
bind -T copy-mode-vi C-h select-pane -D
bind -T copy-mode-vi C-t select-pane -U
bind -T copy-mode-vi C-n select-pane -R
bind -T copy-mode-vi C-\ select-pane -l
```

However, now I could not move to the tmux pane from the vim window when on normal mode. The only key is C-h but this moves the window to the left, not down. Actually the `h` key on the Dvorak keyboard is positioned on the `j` key  on QWERTY, so I think somewhere it is mapped inproparly. 

Sorry for my misunderstanding...

**Comment by YOnoda** [comment]
Hi,

Sorry again that the problem is that I use Dvorak, and I only changed the first part of the following keys to my Dvorak setting (e.g mine was `bind -n **C-d** if-shell "$is_vim" "send-keys **C-h**"  "select-pane -L"`). 

The following code does make the cursor move on the insert mode working fine.

```
bind -n C-d if-shell "$is_vim" "send-keys C-d"  "select-pane -L"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -D"
bind -n C-t if-shell "$is_vim" "send-keys C-t"  "select-pane -U"
bind -n C-n if-shell "$is_vim" "send-keys C-n"  "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind -T copy-mode-vi C-d select-pane -L
bind -T copy-mode-vi C-h select-pane -D
bind -T copy-mode-vi C-t select-pane -U
bind -T copy-mode-vi C-n select-pane -R
bind -T copy-mode-vi C-\ select-pane -l
```

However, now I could not move to the tmux pane from the vim window when on normal mode. The only key is C-h but this moves the window to the left, not down. Actually the `h` key on the Dvorak keyboard is positioned on the `j` key  on QWERTY, so I think somewhere it is mapped inproparly. 

Sorry for my misunderstanding...

**Comment by YOnoda** [comment]
Hi,

Sorry again that the problem is that I use Dvorak, and I only changed the first part of the following keys to my Dvorak setting (e.g mine was `bind -n **C-d** if-shell "$is_vim" "send-keys **C-h**"  "select-pane -L"`). 

The following code does make the cursor move on the insert mode working fine.

```
bind -n C-d if-shell "$is_vim" "send-keys C-d"  "select-pane -L"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -D"
bind -n C-t if-shell "$is_vim" "send-keys C-t"  "select-pane -U"
bind -n C-n if-shell "$is_vim" "send-keys C-n"  "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind -T copy-mode-vi C-d select-pane -L
bind -T copy-mode-vi C-h select-pane -D
bind -T copy-mode-vi C-t select-pane -U
bind -T copy-mode-vi C-n select-pane -R
bind -T copy-mode-vi C-\ select-pane -l
```

Actually, I found one more step necessary. I added the following on the vim initialization file and then worked perfectly. 

```
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <C-d> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-h> :TmuxNavigateDown<cr>
nnoremap <silent> <C-t> :TmuxNavigateUp<cr>
nnoremap <silent> <C-n> :TmuxNavigateRight<cr>
nnoremap <silent> <C-/> :TmuxNavigatePrevious<cr><Paste>
```

Sorry for my misunderstanding...

**Comment by YOnoda** [comment]
Hi,

Sorry again that the problem is that I use Dvorak, and I only changed the first part of the following keys to my Dvorak setting (e.g mine was `bind -n **C-d** if-shell "$is_vim" "send-keys **C -h**"  "select-pane -L"`). 

The following code does make the cursor move on the insert mode working fine.

```
bind -n C-d if-shell "$is_vim" "send-keys C-d"  "select-pane -L"
bind -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -D"
bind -n C-t if-shell "$is_vim" "send-keys C-t"  "select-pane -U"
bind -n C-n if-shell "$is_vim" "send-keys C-n"  "select-pane -R"
bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind -T copy-mode-vi C-d select-pane -L
bind -T copy-mode-vi C-h select-pane -D
bind -T copy-mode-vi C-t select-pane -U
bind -T copy-mode-vi C-n select-pane -R
bind -T copy-mode-vi C-\ select-pane -l
```

Actually, I found one more step necessary. I added the following on the vim initialization file and then worked perfectly. 

```
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <C-d> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-h> :TmuxNavigateDown<cr>
nnoremap <silent> <C-t> :TmuxNavigateUp<cr>
nnoremap <silent> <C-n> :TmuxNavigateRight<cr>
nnoremap <silent> <C-/> :TmuxNavigatePrevious<cr><Paste>
```

Sorry for my misunderstanding...
