### ISSUE TITLE
Difference between using if vs run shell in tmux

### ISSUE THREAD

**Issue by himat** [christoomey/vim-tmux-navigator#232]
This is a tmux question about why I can't seem to use `run-shell` instead of `if-shell` for the tmux configuration.

Using C-l below works to go right through both vim and tmux, but the C-h only goes left through tmux panes and ignores vim splits. Is there something wrong with how I'm evaluating the `is_vim` variable command?

tmux.conf:
```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-h run-shell "if [ $is_vim ]; then tmux send-keys C-h; else tmux select-pane -L; fi"
```

**Comment by christoomey** [comment]
Hi @himat, I'm honestly not sure about the differences beyond the fact that `if-shell` is tailor-made for our use case with the three shell commands and conditional handling. Not sure if there is something specific leading you to try to use `run-shell` instead, but I'd not recommend it and don't have much to offer in the way pointers. Sorry I can't be of more help, but if you're still hoping to figure this out, I think StackOverflow is likely a better spot to get answers.
