### ISSUE TITLE
Cannot navigate between tmux panes with ssh, but with sshpass it works

### ISSUE THREAD

**Issue by xxyxxyxyx1** [christoomey/vim-tmux-navigator#236]
I have two tmux panes. In one pane, I ssh into one of many remote servers. I start things like this:
    `tmux`
    `tmux splitw -h -p 50`
At this point, I can navigate between the panes as expected. 

If in one pane I do:
    `ssh user@server.com`
then I cannot navigate out of that pane, and `<c-l>` clears the prompt. I can navigate to the other pane using `<c-b> <arrow>`, and then I can go back to the ssh pane with `<c-h>`. 

However, if instead I do:
    `sshpass ssh user@server.com`
then everything works as expected. 

What's going on? Prepending `sshpass` to all of my `ssh` commands gets the job done, but I'd like to understand it, and I don't want to rely on such a questionable tool as sshpass

On the local machine I'm using:
macOS 10.14.5, Terminal.app, tmux 2.9a, OpenSSH_7.9p1, LibreSSL 2.7.3, sshpass 1.06

**Comment by christoomey** [comment]
Hi @xxyxxyxyx1, unfortunately I don't have much experience working with mixed SSH + tmux contexts like this and can't offer much in the way of suggestions as to what the issue or possible solution is. I'd suggest taking the question to StackOverflow or similar to get a more general help. I'm going to close this for now as I don't believe there are any issues specific to vim-tmux-navigator here, but please feel free to comment or reopen if you think I'm missing something or if you find a solution / an issue with the plugin.
