### ISSUE TITLE
Failed switch between panels when inside Termdebug window

### ISSUE THREAD

**Issue by ingjieye** [christoomey/vim-tmux-navigator#239]
So I have vim inside Tmux. Everything's works great. 
Bug after VIM 8.1, there's a feature called Termdebug that I can run gdb inside VIM. 
It'll open some panels inside VIM.
When I'm inside debug panel inside VIM. I can't switch between panels as usual.

<img width="1440" alt="" src="https://user-images.githubusercontent.com/13421169/62695245-824b7a00-ba08-11e9-84bc-ffabc11e029e.png">

**Comment by christoomey** [comment]
Hi @ingjieye. Can you test a few things? 

- What is the output of `:verbose nmap <C-k>` when run in the gdb pane?
- Does running `:TmuxNavigateUp` directly work, or similarly fail?

**Comment by ingjieye** [comment]
- `:verbose nmap <C-k>`:
```
n  <C-K>       * :TmuxNavigateUp<CR>
        Last set from ~/.vim/plugged/vim-tmux-navigator/plugin/tmux_navigator.vim line 21
```

- Directly running :TmuxNavigateUp inside gdb pane works.

I notice that gdb pane inside Vim is just a gdb running inside vim embedded terminal. 
So turns out that the problem is how to map shot-cuts inside vim-term. 

I've paste this pr's change into my .vimrc. https://github.com/christoomey/vim-tmux-navigator/pull/172/commits/63120c1997ccf97feb0cb924425c4f2eec0df443. I can switch pane between Vim and Tmux. 

Except that when I switch out of vim-term. 

<img width="306" alt="屏幕快照 2019-08-09 上午9 42 43" src="https://user-images.githubusercontent.com/13421169/62748149-17db1e00-ba8a-11e9-97b0-68c1c5a3ee75.png">

<img width="346" alt="屏幕快照 2019-08-09 上午9 43 01" src="https://user-images.githubusercontent.com/13421169/62748159-2295b300-ba8a-11e9-9e76-68e8f7651112.png">

The vim-term pane goes into text mode that when I switch back I have to press `a` to get it working. 

So I've changed a little bit into
```
if exists(':tnoremap')
 tnoremap <silent> <c-h> <c-w>:TmuxNavigateLeft<cr>
 tnoremap <silent> <c-j> <c-w>:TmuxNavigateDown<cr>
 tnoremap <silent> <c-k> <c-w>:TmuxNavigateUp<cr>
 tnoremap <silent> <c-l> <c-w>:TmuxNavigateRight<cr>
 tnoremap <silent> <c-\> <c-w>:TmuxNavigatePrevious<cr>
endif
```

Every thing works fine. 
I also have FZF installed and when I navigate FZF result with `Ctrl + k / Ctrl + j`. It haven't conflict as discussed in 
https://github.com/christoomey/vim-tmux-navigator/pull/172
https://github.com/christoomey/vim-tmux-navigator/issues/128
