### ISSUE TITLE
Cannot switch from nvim to tmux pane

### ISSUE THREAD

**Issue by meatballs** [christoomey/vim-tmux-navigator#240]
I've had a working config for some time on my MacBook and I've copied it to a new machine running Ubuntu 19.10, but now cannot switch out of a pane running neovim into a tmux pane. (Switching between tmux panes or from a tmux pane to neovim works fine).

neovim init.vim (installation via vim-plug):
```
call plug#begin()

" Common navigation of tmux and nvim windows
Plug 'christoomey/vim-tmux-navigator'

call plug#end()
```

tmux.conf:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run -b '~/.tmux/plugins/tpm/tpm'
```

output from `:verbose nmap <C-j>` in neovim:
```
n  <NL>        * :TmuxNavigateDown<CR>
        Last set from ~/.config/nvim/plugged/vim-tmux-navigator/plugin/tmux_navigator.vim
```

I've also tried running `:TmuxNavigateDown` directly from within neovim to ensure it's not a key binding issue and nothing happens.

I'm on tmux 2.9 and neovim 0.3.8

**Update**
I've now tried this with vim (rather than neovim) and it's also not working there.
I was also on tmux 2.8 on my MacBook, so I updated to 2.9 and it all still works perfectly.

**Comment by christoomey** [comment]
Hmm, that's surprising. Can you clarify if this happens in all directions? Also, can you confirm the output for each direction of the vim keybinding?

``` vim
:verbose nmap <C-h>
:verbose nmap <C-j>
:verbose nmap <C-k>
:verbose nmap <C-l>
```

**Comment by meatballs** [comment]
It's the same in all directions - not working from within neovim but working from tmux.

The nmap output for each binding is TmuxNavigateLeft, TmuxNavigateRight etc. as expected.

Each of those commands does nothing when run directly in neovim.

**Comment by meatballs** [comment]
Anything else I can do to debug this?

**Comment by meatballs** [comment]
**SOLVED**
My nvim config set the `shell` variable to the path to bash - however, it was using the Mac's version of that path rather than the correct path on Ubuntu. All working perfectly now that the correct path is in there.

**Comment by geofflangenderfer** [comment]
> **SOLVED**
> My nvim config set the `shell` variable to the path to bash - however, it was using the Mac's version of that path rather than the correct path on Ubuntu. All working perfectly now that the correct path is in there.

What did you change?

**Comment by victorb** [comment]
@geoffharcourt probably you've already solved it by now, but I also found this thread in my quest to solve this issue.

In the end, added `default-shell` and `shell` to both tmux and nvim config solved the issue, pointing them to the same shell.

```
# tmux config
set-option -g default-shell /run/current-system/sw/bin/zsh
```

```
# nvim config
set shell=/run/current-system/sw/bin/zsh
```

Obviously you'd want the value of `default-shell` and `shell` to point correctly to what shell you wanna use, which might be different than above.
