### ISSUE TITLE
If I switch between two vim windows, audo save does not work.

### ISSUE THREAD

**Issue by Shandun** [christoomey/vim-tmux-navigator#241]

**Comment by christoomey** [comment]
Hi @Shandun, the autosave functionality is only intended to work when navigating from Vim to tmux, but does not fire when navigating between two vim windows.

If you'd like to have autosave when navigating between vim windows you could implement that entirely outside this plugging by adding something like the following to your vimrc:

``` vim
autocmd BufLeave * update
```

Hope that helps!

**Comment by Shandun** [comment]
Hi @christoomey , your solution works perfectly! That's what I really want for weeks. Thanks very much!
