### ISSUE TITLE
Cannot navigate vim panes - only tmux panes [POSSIBLE SOLUTION]

### ISSUE THREAD

**Issue by NathanCummings** [christoomey/vim-tmux-navigator#255]
So I don't know if it is appropriate to submit this as an issue - because it seems to be fine now - but the solution *may* help others.

I couldn't navigate vim panes, only Tmux. I could call the :TmuxNavigate<> commands manually and that was fine, so there seemed to be some issue with the 'is_vim' check. I ran 'tmux ls' and saw that I had **another session from before I installed the plugin** open, so I ran 'tmux kill-server' so I had no sessions whatsoever, then opened a new one. Everything appears to work fine now.

I can't tell you exactly why this worked, but it did, so if anyone else has this issue it might be worth a shot.

**Comment by christoomey** [comment]
Hmmm, this is interesting. I wouldn't necessarily expect having nested tmux sessions to behave this way, but at the same time, I know tmux pretty strongly tries to keep us from having nested sessions, so not surprising that it broke something :)

Just for completeness-sake, in case someone else finds this issue down the road, I'm guessing you discovered this by running the `:TmuxNavigatorProcessList` command, correct?

Either way, thanks for sharing this. I'm going to close the issue now as I don't think there is anything else to address here, but I (and likely someone else with this same issue) appreciate you documenting this so folks might be able to find it in the future. Cheers!

**Comment by NathanCummings** [comment]
Just to clarify, this wasn't a nested session. It was just a single session that had been running from before I installed the plugin. Once I had killed it so I had no Tmux server running, the bindings started behaving. Many thanks for the plugin!
