### ISSUE TITLE
unintuitive jumping between panes

### ISSUE THREAD

**Issue by henningphan** [christoomey/vim-tmux-navigator#256]
Given 3 vertical tmux panes. |T0|T2|T3|, and then We start vim in T0 and make 2 panes.

|V0|V1|T2|T3|

Let * denote my current active pane, then I expect C-L to wrap around between pane:
 0, 1, 2 ,3, 0, 1 , 2, 3

|V0*|V1|T2|T3|
|V0|V1*|T2|T3|
|V0|V1|T2*|T3|
|V0|V1|T2|T3*|
|V0*|V1|T2|T3|
|V0|V1*|T2|T3|
|V0|V1|T2*|T3|
|V0|V1|T2|T3*|

But what actually happens is
0, 1, 2, 3, 1, 2, 3, 1 ,2 ,3

|V0*|V1|T2|T3|
|V0|V1*|T2|T3|
|V0|V1|T2*|T3|
|V0|V1|T2|T3*|
|V0|V1*|T2|T3|
|V0|V1|T2*|T3|
|V0|V1|T2|T3*|

**Comment by christoomey** [comment]
Hi @henningphan, I believe what you're discussing is captured in https://github.com/christoomey/vim-tmux-navigator/issues/70, https://github.com/christoomey/vim-tmux-navigator/pull/221, and https://github.com/christoomey/vim-tmux-navigator/pull/237. I've yet to come to any conclusion on that front, but I think those issues are sufficient to capture the idea, so I'm going to close this issue.
