### ISSUE TITLE
Unknown command error

### ISSUE THREAD

**Issue by Espenol** [christoomey/vim-tmux-navigator#259]
First time configuring tmux, please forgive the (probably) noob question; I followed your instructions and attempted to add the code snippet to get this navigator. Did not work, so I tried the plugin approach. My .tmux.conf looks as follows: 
```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

Both approaches give me the following error:
`/home/user/.tmux.conf:1: unknown command:`

It is just blank unknown command. That is likely because my first line is a comment. If I eliminate the first line in the .tmux.conf-file shown above, I get 
'/home/user/.tmux.conf:1: unknown command: set'

No matter what command I set first, I get 'unknown command'. What gives? Does tmux not like me? Is there some essential tmux configuration that I am missing?

**Comment by christoomey** [comment]
Hmm, my best guess is that this is a general tmux issue as opposed to something specific to this plugin, but happy to try to talk you through it.

Couple of quick thoughts:

1. Which tmux version are you using (you can list it with `tmux -V`)
2. Does tmux start with an empty `~/.tmux.conf file`?
3. How are you starting tmux?

**Comment by Espenol** [comment]
Thank you for your quick response! Answers as follows:
1. tmux 2.8
2. It starts just fine with an empty conf file. 
3. I start tmux by writing `tmux` in my WSL Debian terminal

Maybe I should open an issue on the tmux github instead and link it here? (If that is possible... slightly new to Github)

**Comment by Espenol** [comment]
It appears there were bom characters at the start of the file which caused the error. See the [issue I raised ](https://github.com/tmux/tmux/issues/2181) at the tmux issue tracker.
