### ISSUE TITLE
can't install with plugged

### ISSUE THREAD

**Issue by lpanebr** [christoomey/vim-tmux-navigator#260]
I've added  `Plug 'christoomey/vim-tmux-navigator'` to my `nvim/init.vim` like I do for the other plugins but **PlugInstall** seems to ignore it and does not install..

Any idea?

**Comment by christoomey** [comment]
Nope, definitely should be installable via `Plug`. Any specific error or behavior? Does it show up in the list at all when you run `PlugInstall`? Just to confirm, did you re-source your vimrc (`:source $MYVIMRC`, or just restart vim) before running `PlugInstall`? Just throwing out ideas.

Overall I would not think this is an issue with the plugin, so with that in mind I'm going to close this issue, but feel free to comment or reopen if you think I've missed anything (or if you're able to resolve!).

**Comment by lpanebr** [comment]
> Thank you for you quick reply!

I should've posted this to the plugged repo actually. ;-)

**Comment by lpanebr** [comment]
I'm not sure what happened but today it installed!
