### ISSUE TITLE
Neovim issues

### ISSUE THREAD

**Issue by pianocomposer321** [christoomey/vim-tmux-navigator#261]
Here's my ~/.tmux.conf:

```
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
```

\<C-h>, \<C-l>, etc switch between neovim splits and also from neovim to tmux, but not from tmux to neovim.

**Comment by christoomey** [comment]
Hmm, sounds like Vim is properly wired up, but tmux is not for some reason. Can you check the output of `tmux list-keys` and see if it contains the expected key bindings with all the `"$is_vim"...` stuff? Possible you have conflicting mappings in your tmux config that are overriding.

**Comment by pianocomposer321** [comment]
@christoomey Thanks for your reply. Sorry, I had forgotten that I opened this issue too. I opened one on the tmux repo and I already got an answer there. The problem was Unix vs windows line endings. I could tell because the last four lines of `tmux list-keys | grep C-[hjkl]` (which were the relevant key bindings) had a \r at the end of them. Anyway, I fixed it using dos2unix. The issue is [here ](https://github.com/tmux/tmux/issues/2210)if anyone wants to see it.

BTW, I had changed my tmux.conf to this:

```
# smart pane switching with awareness of vim splits
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"
```

(copied and pasted from [this](https://thoughtbot.com/blog/seamlessly-navigate-vim-and-tmux-splits) website)
Because the above wasn't working. I don't know if dos2unix would have fixed it, but it doesn't really matter. It's working now and that all that matters to me.
