### ISSUE TITLE
Switching splits within nvim extremely slow

### ISSUE THREAD

**Issue by joshfrench** [christoomey/vim-tmux-navigator#262]
Using the provided mappings (`<C-h>`, etc) nvim pauses for ~5 seconds before switching splits. However, if I call `:TmuxNavigateLeft` directly it performs as expected.

I don't see a conflicting mapping:

```
:verbose map <C-h>
n  <C-H>       * :TmuxNavigateLeft<CR>
        Last set from ~/.local/share/nvim/plugged/vim-tmux-navigator/plugin/tmux_navigator.vim line 19
```

I've reproduced this with an empty `.zshrc`/`.zshenv`, and given that it seems specific to the mapping and not the command, I don't think this is the same as #72 .

**Comment by christoomey** [comment]
Hi @joshfrench, I think there are two possibilities:

1. nvim is waiting after receiving the `<C-h>` key sequence to see if you will type more characters. It would do this if you had other mappings that include `<C-h>`, e.g. `<C-h>j` (ctrl-h followed by j), but based on the output from the `verbose map <C-h>` it doesn't look like that's the case (unless there was other output that you did not include here).
2. Tmux / your shell is taking a while to evaluate the `$is_vim` check. You could test this by modifying the tmux.conf lines to just print a message

``` diff
- bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
+ bind-key -n 'C-h' if-shell "$is_vim" 'display-message "hello"'  'select-pane -L'
```

From that, you might be able to determine if the slowdown is in the tmux command or shell command for matching vim.

**Comment by joshfrench** [comment]
This is definitely a tmux thing. Thanks for the lead and sorry for the false alarm!

**Comment by ghwatson** [comment]
@christoomey did you find a solution from the tmux-side? having this issue as well

**Comment by joshfrench** [comment]
@ghwatson The problem was in `if-shell`, but my investigation didn't go any further than that. I ended up reverting to an implementation that doesn't rely on a shell call to check the condition: https://github.com/christoomey/vim-tmux-navigator/pull/266/files

YMMV!

**Comment by ghwatson** [comment]
Worked perfectly for me, thanks!

**Comment by tmm** [comment]
Same thing was happening to me and [this comment helped](https://github.com/christoomey/vim-tmux-navigator/issues/72#issuecomment-103578088). (I am using fish shell.)

**Comment by agirorn** [comment]
I have to admit I find it strange that this issue is closed. Since this is still an issue and does not work for some users out of the box.

Is there a plan in could we fix this permanently in the plugin?
Could we revert back to the old behavior where the shell is not used to detect vim?
