### ISSUE TITLE
How to refresh the screen?

### ISSUE THREAD

**Issue by vext01** [christoomey/vim-tmux-navigator#265]
I like the default bindings, but we overwrite ctrl-l, which is traditionally 'refresh'.

Is there a way (or could there be a way) to refresh the screen? E.g. ctr-l twice in quick succession?

**Comment by christoomey** [comment]
https://github.com/christoomey/vim-tmux-navigator#restoring-clear-screen-c-l 😉

**Comment by vext01** [comment]
Thank you!
