### ISSUE TITLE
[FEATURE_REQUEST] Restore zoom after leaving auto zoomed panel

### ISSUE THREAD

**Issue by vignesh0025** [christoomey/vim-tmux-navigator#267]
We already have a feature which restores the other pane when jumping from a Zoomed pane. It would be a nice feature on automatically zoom the previous window on leaving the restored pane if it was initially zoomed.

 *means active pane
`------------------`
`Pane 1* (Zoomed)     |  Pane  2`
`------------------`

`On Moving to pane 2`         -> **This is already present**
`-----------------`
`Pane 1         |         Pane  2*  `
`-----------------`

*Now when moving back to Pane 1, Its previous zoom state is restored*
`----------------------------`
`Pane 1* (Auto Zoom Restore)     |  Pane  2`
`----------------------------`

I gave a graphical idea since I couldn't properly express the idea with just words. Please add this feature. I am finding it quite difficult with vimscript to make the change myself.

**Comment by christoomey** [comment]
Hi @vignesh0025, thanks for sharing this. The behavior you're highlighting (automatically collapsing the zoomed pane back to normal when you navigate out) is actually coming from tmux, not this plugin.

In the end my goal here is to keep things as simple as possible. That said, I have another plugin, [vim-tmux-runner](https://github.com/christoomey/vim-tmux-runner), which implements additional functionality. In particular, there is a command `:VtrFocusRunner` which likely is close to what you're looking for.

Hopefully that helps. I'm going to close this issue now as I don't think there are any changes to make here.

**Comment by vignesh0025** [comment]
I got the idea how to get it working much better with vim-tmux-runner. However, I got another issue with nvim and vim-tmux-runner specifically. Please look into  christoomey/vim-tmux-runner#100 .
