### ISSUE TITLE
Tmux/Tmate/Vim navigation not working

### ISSUE THREAD

**Issue by pzula** [christoomey/vim-tmux-navigator#27]
Hello!

Thank you for this great package!

I love this plugin, but have recently noticed an issue when using [tmate](http://tmate.io) that my keybindings don't seem to work.

When I run `:TmuxPaneCurrentCommand`, I get this output:
`protocol version mismatch (client 8, server 7)`

This is pane-ful (get it?) when using tmate to pair with others remotely, as I've grown accustomed to navigating in vim normally while in tmux. Do you have any suggestions on how I can work around this? I am using Mac OSX Mavericks, homebrew, and iTerm.

**Comment by jondkinney** [comment]
I'm running Yosemite and tried to downgrade to tmux 1.8. When you start tmux it says something to the effect of: "warning this version is unsupported, please upgrade to 1.9a". I also use tmuxinator which uses some of the new `-c` stuff (I guess?) and so it didn't work either. Hopefully we can get tmate upgraded to 1.9a soon, but unfortunately it looks like the author hasn't had time for the last year to update it https://github.com/nviennot/tmate/issues/33
