### ISSUE TITLE
Default tmux bindings everywhere?

### ISSUE THREAD

**Issue by aaccioly** [christoomey/vim-tmux-navigator#272]
Hi guys,

I don't know if this is useful (maybe as an option or as part of the documentation), but I've managed to get the plugin  working with tmux default bindings (C-b Left, C-b Right, C-b Up, C-b Down, C-b ;) instead of vim.

### tmux.conf
 
```shell
is_vim_pane_no_mode="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$' \
    && [ '#{pane_in_mode}' -eq 0 ]"
bind-key -r -T prefix 'Left'  if-shell "$is_vim_pane_no_mode" 'send-keys C-b Left'    'select-pane -L'
bind-key -r -T prefix 'Down'  if-shell "$is_vim_pane_no_mode" 'send-keys C-b Down'    'select-pane -D'
bind-key -r -T prefix 'Up'    if-shell "$is_vim_pane_no_mode" 'send-keys C-b Up'      'select-pane -U'
bind-key -r -T prefix 'Right' if-shell "$is_vim_pane_no_mode" 'send-keys C-b Right'   'select-pane -R'
bind-key    -T prefix '\;'    if-shell "$is_vim_pane_no_mode" 'send-keys C-b \\'      'select-pane -l'
```

### .vimrc
```shell
nnoremap <silent> <C-b><Left> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-b><Down> :TmuxNavigateDown<cr>
nnoremap <silent> <C-b><Up> :TmuxNavigateUp<cr>
nnoremap <silent> <C-b><Right> :TmuxNavigateRight<cr>
nnoremap <silent> <C-b>\ :TmuxNavigatePrevious<cr>
```

### Limitations

1. When pane is in copy-mode you can't navigate to inner vim splits (this is also happening with default bingings).
2.  For some I can't, for the life of mine, make send-keys send a ";" to vim, so I'm mapping ; to \.

Tested with tmux 2.7.

**Comment by christoomey** [comment]
Hi @aaccioly, thanks for sharing this! While I appreciate you writing this up, I think this issue will serve well enough if anyone else comes searching for this specific tweak (and we've already got more general notes in the readme), so I'm going to close this, but please feel free to comment or reopen if you think I missed anything.

**Comment by aaccioly** [comment]
@christoomey , it's ok to close.
I guess that the only thing that I would like to add is that by using `#{pane_in_mode}` like I did above you could also make your original tmux config code snippet shorter.

More specifically, the following statements are no longer necessary. 

``` shell
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
```
The `if-shell` from my version above flows to the default commands (`select-pane` / else path) when a pane is in copy-mode.

It's a small improvement, and I haven't tested it with older versions of tmux, but it may be worth investigating.
