### ISSUE TITLE
tmux version detection doesn't work on some prereleases

### ISSUE THREAD

**Issue by matthewstrasiotto** [christoomey/vim-tmux-navigator#278]
tmux's versioning is "colorful" to, and its release strings are not particularly consistent. 
The current head of the tmux repo has a release string: `"tmux next-3.3"`. 

Your current `sed` command does not correctly extract the numeric component of this.
#276 resolves this, and the more important problem that when this is used as a TMP plugin, `if-shell` needs to be invoked as a subcommand of `tmux`, rather than directly, as TMP plugins are run as bash scripts, not tmux scripts

**Comment by christoomey** [comment]
I believe this is handled by #276, so closing this issue.
