### ISSUE TITLE
Let mappings be configurable by tmux options for plugin

### ISSUE THREAD

**Issue by matthewstrasiotto** [christoomey/vim-tmux-navigator#279]
For example, the following options might alias the same mapping to Ctrl+:
- The arrow keys
- the "home row" vim-style keys, &
- WASD

```
set -g @vim_tmux_navigator_arrow_mappings 'true'
set -g @vim_tmux_navigator_hjkl_mappings 'true'
# I'm aware that the following may already have bindings or collide, but i wanted to give a demo
set -g @vim_tmux_naviagtor_custom_L 'C-a'
set -g @vim_tmux_navigator_custom_R 'C-d'
set -g @vim_tmux_navigator_custom_U 'C-w'
set -g @vim_tmux_navigator_custom_D 'C-s'
```

**Comment by christoomey** [comment]
My inclination is to suggest that folks move to the manual configuration (adding the relevant lines to their ~/.tmux.conf). I'd like the TPM version to be the true "just install it and it works version", with any escape hatches described for the manual version.

None the less, I appreciate the note!
