### ISSUE TITLE
README: git clone command

### ISSUE THREAD

**Issue by jsign** [christoomey/vim-tmux-navigator#285]
I'm not sure if in some previous Vim version the `git clone` command mentioned in the README works, but for Vim 8.1, the following works:
`git clone git@github.com:christoomey/vim-tmux-navigator.git ~/.vim/pack/plugins/start/vim-tmux-navigator`

If confirmed this is OK as general advice, I can create a PR.

**Comment by christoomey** [comment]
Hmm, I’ve personally never used it (I’ve used vundle or vim-plug always). I’d happily accept a pull request if you’re able to sort through the details and current command. Thanks!
