### ISSUE TITLE
Different OS?

### ISSUE THREAD

**Issue by Nazar-Petsentii** [christoomey/vim-tmux-navigator#305]
I'm using macOS 11.6 and : TmuxNavigatorProcessList shows this info:
Ss   -zsh
S    -zsh
S    /Users/nazarpetsentii/.cache/gitstatus/gitstatusd-darwin-x86_64
S+   vim
S+   tmux
Is it OK? Because my vim and Tmux navigator doesn't work. I have installed vim plugin and checked it with :PluginList
I have added firstly these instructions ```
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm```
Still didn't work. Added a snippet, and it doesn't work. Looking for conflicting patterns showed no matching. Tmux version 3.2

**Comment by Nazar-Petsentii** [comment]
I can't navigate neither between just Tmux panes nor when vim is one of them. It does nothing when I hit keybindings. 
I have restarted my Mac entirely to no avail.

**Comment by christoomey** [comment]
Hi @Nazar-Petsentii, that's surprising that nothing is happening. You could check the output of `tmux list-keys` to confirm that the tmux level bindings are in fact set as a start.
