### ISSUE TITLE
TPM plugin seems to be broken

### ISSUE THREAD

**Issue by schneiderfelipe** [christoomey/vim-tmux-navigator#312]
The instructions [here](https://github.com/christoomey/vim-tmux-navigator#tpm) seem to fail. This is the last twelve or so lines in my `~/.config/tmux/tmux.conf`:

```tmux
# List of tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# Vim/Neovim integration
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# tmux-continuum should be the last one in the plugin list
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize tpm, the tmux plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
```

But things seem not to work. Is this the proper way of configuring?

**Comment by schanzel** [comment]
Same here. Navigating from vim to tmux works, but navigating from a tmux pane to another one (vim or non-vim) doesn't.
```tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
run -b '~/.tmux/plugins/tpm/tpm'
```

**Comment by schanzel** [comment]
I reordered them to load `vim-tmux-navigator` last but with same result.

**Comment by schneiderfelipe** [comment]
@schanzel In this case, I was very wrong. It worked for me as well. No incompatibility actually.
