### ISSUE TITLE
Custom key maps don't work in neovim [solved]

### ISSUE THREAD

**Issue by urob** [christoomey/vim-tmux-navigator#315]
SOLVED: Everything seems to work fine today. I am not exactly sure why. My guess is that it is related to restarting vim and tmux instead of resourcing their configurations. Anyhow, this can be closed.

---

I encountered a very strange issue in NVIM v0.6.1 with tmux 3.2a and with the latest vim-tmux-navigator installed using `vim-plug`. When I set `let g:tmux_navigator_no_mappings = 0` in my vim configuration file (`init.vim` in nvim), then everything works as expected. However, including the defaults defined in `tmux_navigator.vim` directly in my own `init.vim` breaks the configuration:

```
" Loading default bindings works
let g:tmux_navigator_no_mappings = 0 
```

```
" Replicating default bindings myself won't work
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-\> :TmuxNavigatePrevious<cr>
```

With the latter configuration, none of the maps are recognized inside vim, and pressing `c-h` will simply result in `h` etc. It seems that binding keys to the TmuxNavigator from within `init.vim` has no effect (at least when tmux-navigator is installed using [vim-plug manager](https://github.com/junegunn/vim-plug)). 

Note: this is not an issue of conflicting bindings (I have no other bindings involving CTRL). Also, for a quick sanity check: mapping `nnoremap <silent> <c-h> :echo "test"<cr>` works as expected. So it seems to be really something unique about the interaction of nvim and the TmuxNavigator.

(This might be related to: https://github.com/christoomey/vim-tmux-navigator/issues/140)

**Comment by urob** [comment]
As an aside: For anyone simply wanting to change the bindings used for the navigation, there is no need to change the vim configuration. As long as it matches the `send-keys` in the tmux configuration, things will work as expected. In other words, this will work as expected with the default `vimrc`/`init.vim` configuration:

```
# use default send-keys with custom key binding
bind-key -n <custom key here> if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n <custom key here> if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n <custom key here> if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n <custom key here> if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
```

(The one case where this does not work is when one want to recycle `ctrl + h/j/k/l` for other maps inside vim.)

**Comment by ahillio** [comment]
> Anyhow, this can be closed.

You gotta close it yourself... rather than change title, click the button to close the issue ;^)
