### ISSUE TITLE
Tmux process not listed with v3.3a

### ISSUE THREAD

**Issue by RUrlus** [christoomey/vim-tmux-navigator#324]
After updating neovim and tmux I am running into the issue where the plugin no longer works when in a tmux session.

Output of `TmuxNavigatorProcessList`:
```
Ss   /bin/zsh
S+   lvim
```

- **vim:** NVIM v0.8.0
- **Tmux:** tmux 3.3a
- **OS:** MacOS 12.6

Plugin is up-to-date and is managed using tpm on tmux side and Packer on Neovim side.
Tried manual config but that didn't change anything.

**Comment by christoomey** [comment]
It looks like your Vim process is being listed as `lvim`. The [relevant line](https://github.com/christoomey/vim-tmux-navigator/blob/master/vim-tmux-navigator.tmux#L6) from the TPM version of the script will not detect `lvim` as the `l` is not expected.

Not sure why your vim is showing as `lvim`, but if that's not something you can change, you could move off the TPM version of the script and add the [tmux snippet](https://github.com/christoomey/vim-tmux-navigator#add-a-snippet) directly, updating the grep pattern to match `lvim`.

Hope that all helps! Closing this now as I don't believe there is a core issue here.

**Comment by RUrlus** [comment]
Changing the regex solves the issue for me, thanks @christoomey! One quick note, the readme states that one should open an issue if the output is different from:
```
Ss   -zsh
S+   vim
S+   tmux
```
I expected that `tmux` should be listed for me as well, but apparently this is no longer the case(?).
