### ISSUE TITLE
How to open a tmux window with pressing "l"  

### ISSUE THREAD

**Issue by fullhdpixel** [christoomey/vim-tmux-navigator#331]
<C-w> opens the list of windows, these are all my projects I'm working on. Since I'm switching between these a lot, I wanted to remap "l" to opening the file which now requires an Enter. How would one go about remapping l to opening a window in Tmux.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/7371397/206857100-4d2ef180-b43c-4044-9bec-51bd866fa772.png">

**Comment by christoomey** [comment]
Hi @fullhdpixel - I'm not sure I follow exactly what you're asking, but my sense is this isn't directly related to the plugin and so I'm going to close it. Unfortunately I'm not sure how you'd work around the mappings as you seem to be asking here.
