### ISSUE TITLE
Navigation only works in the starting tmux pane.

### ISSUE THREAD

**Issue by MillyP1** [christoomey/vim-tmux-navigator#333]
OS: MacOS Ventura 12.1
Vim: NVIM v0.8.1
Tmux: 3.3a

I can only navigate between vim panes if it's open in the "original" tmux pane. If I split tmux vertically and open vim in the right pane (the created pane) then split vim vertically, I'm only able to navigate between vim and tmux. Hopefully, that makes sense. 

Opening vim in the "original" tmux pane and splitting vim there is the only place I can navigate seamlessly.

I ran `:TmuxNavigatorProcessList` in the "original" pane and it would output:
```
Ss   /bin/zsh
S    /bin/zsh
S    /bin/zsh
S    /bin/zsh
S    /Users/milly/.cache/gitstatus/
Z    <defunct>
S+   nvim
```

Running the same command in a split pane of tmux then entering vim outputs:
```
Ss+ zsh (figterm)
```

I noticed the "(figterm)", would that maybe influence this problem? Since configuring iTerm with neovim via Josean's video, Fig doesn't work anymore so I figured I didn't need to uninstall it. Or I don't know if this is an unrelated issue.
Regardless, any help would be appreciated :) I'm all very new to this

**Comment by MillyP1** [comment]
The issue was with Fig. I uninstalled refreshed Tmux. Everything works fine now.

**Comment by ghry5** [comment]
For anyone hitting this issue. You can get it working with fig by using an approach like: https://github.com/christoomey/vim-tmux-navigator/issues/295#issuecomment-1123455337
