### ISSUE TITLE
Tmux -> Neovim not working

### ISSUE THREAD

**Issue by Dannygx21** [christoomey/vim-tmux-navigator#347]
I am having an issue navigating within tmux. The key bindings do not navigate between panes. But if I have one pane using neovim and another on tmux terminal I can navigate to the tmux terminal but not back to neovim. 

I am using Mac OS Monterey 12.6.3

Hints to fix:
- `<ctr-l>` clears terminal
- after running tmux "leader + I" =>  "vim-tmux-navigator" download fail
- `:TmuxNavigatorProcessList` returns:
```
Ss   -zsh
S    -zsh
S    -zsh
S    -zsh
S    /Users/Daniel/.cache/gitstatus/gitstatusd-darwin-x86_64
S+   nvim
```

**Comment by christoomey** [comment]
> after running tmux "leader + I" => "vim-tmux-navigator" download fail

It sounds like the tmux plugin is failing to install. That would explain why the navigation isn't working for the tmux side, but is for the vim side.

Not sure why that is failing, but if you resolve that I expect you'll be OK. Given that I'm going to close this issue as I don't think it's actually an issue with the plugin, but please feel free to comment or reopen if you feel there is an issue here.

**Comment by Dannygx21** [comment]
Thank you for the help, I did not find the issue keeping me from downloading the vim-tmux-navigator plugin with TPM (TMUX Plugin Manager), I ended it up downloading manually. Plugin is working 100% as designed.

**Comment by Carltoffel** [comment]
I had the same issue, because I accidentally wrote `tmux-plugins/vim-...` instead of `christoomey/vim-...` in `set -g @plugin 'christoomey/vim-tmux-navigator'`.
