### ISSUE TITLE
Can I make it use CTRL+SHIFT+vi for navigation instead of CTRL+vi 

### ISSUE THREAD

**Issue by rew1nter** [christoomey/vim-tmux-navigator#348]
I'm using bash vi mode. So when using this plugin `Ctrl+l` does its job of navigation but takes away the clear screen ability. Currently I can only think of adding `shift` to either the navigation or to the clear screen command. What are some other workarounds for this conflict?

**Comment by Verisana** [comment]
In case you didn't see the FAQ, there is a workaround:
https://github.com/christoomey/vim-tmux-navigator#restoring-clear-screen-c-l

**Comment by christoomey** [comment]
@Verisana thanks for sharing link to the readme section on this. I'm going to close the issue now as I think that section largely covers the issue.
