### ISSUE TITLE
Can no navigate nvim -> tmux (TmuxNavigatorProcessList doesn't show what is needed)

### ISSUE THREAD

**Issue by Verisana** [christoomey/vim-tmux-navigator#349]
Hello folks,
Thank you very much for your awesome plugin. Unfortunately, I was not able to fully enjoy it since my mapping is not working.

OS: Ubuntu 22.04.2 LTS
NVIM v0.8.3
tmux 3.2a
Plugin is latest from master
Using LazyVim configurations

Command `TmuxNavigatorProcessList` shows:
```
S zsh
S nvim
```

On the left is nvim and terminal on the right pane.
From tmux to nvim is switching ok with C+h, but later from nvim can not jump right.

As terminal I use `Alacritty` and `i3` WM. Don't know if it is important.

What might be the reason of this?

I checked through `which-key` mapping clashes and didn't find anything :(

**Comment by Verisana** [comment]
Sorry, I think I just have mapping conflict in LazyVim:
https://github.com/LazyVim/LazyVim/blob/86ac9989ea15b7a69bb2bdf719a9a809db5ce526/lua/lazyvim/config/keymaps.lua#L21

**Comment by alf5** [comment]
having same issue - sorry im new to this - how did you fix it?
