### ISSUE TITLE
the ctrl+h mapping interrupts the ctrl+backspace mapping

### ISSUE THREAD

**Issue by rew1nter** [christoomey/vim-tmux-navigator#354]
This might not be the place to ask this but.. yeah

Earlier I had this in my terminal `"\C-h": backward-kill-word` to delete a word with `ctrl + bak`. The terminal recognizes the `ctrl+backspace` as `ctrl+h`. So the previous mapping I had is not working anymore. Is there any way to make these two work differently?

**Comment by christoomey** [comment]
Couple options as far as I can tell:

- Make the `C-h` mapping doubly fancy w/ a nested ternary type check. Something like `bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'if-shell $is_zsh ...'`. To be honest I'm not even sure if that (the nested bit) would work, and if it did I'm sure the escape sequences would be maddening, but that's likely the most complete option
- You could map `prefix C-h` to some other sequence which triggers backward-kill-word, similar to the notes on [Restoring Clear Screen (C-l)](https://github.com/christoomey/vim-tmux-navigator#restoring-clear-screen-c-l). Again, a bit messy & indirect, but might be a solution.

I'm going to close this as I this isn't an issue per se, but hopefully these notes provide some direction.

**Comment by SailReal** [comment]
@rew1nter may I ask how did you solve it for you?
