### ISSUE TITLE
Is it possible to switch the window when the terminal is active?

### ISSUE THREAD

**Issue by foozzi** [christoomey/vim-tmux-navigator#367]
When the terminal window (vim term) is active, I can't switch to other windows with ctrl+hjkl, I need to use ctrl+w+hjkl

Is there no solution?

**Comment by christoomey** [comment]
Not supported directly, but should be something you can enabled / configure. See https://github.com/christoomey/vim-tmux-navigator/pull/313 for more details.

Going to close this now as I think the other linked issues (and the ones that one links to) better capture the situation, but please feel free to comment if you think I missed somthing.
