### ISSUE TITLE
Will this plugin support C-Up / C-Down / C-Left / C-Right to resize tmux or vim split ?

### ISSUE THREAD

**Issue by MontiL** [christoomey/vim-tmux-navigator#372]
If this plugin can support C-Up / C-Down / C-Left / C-Right to resize tmux or vim split,
That will be pretty nice !

**Comment by christoomey** [comment]
Hey @MontiL - appreciate the note, but this is not something I intend to support in this plugin. Please see #109, #196, and #314 for a bit more discussion and context, and some pointers as to how you could implement outside this plugin.

**Comment by MontiL** [comment]
by the way, how you resuze the split size of tmux or vim ?
