### ISSUE TITLE
Takes tmux out of minimized mode.

### ISSUE THREAD

**Issue by shibisuriya** [christoomey/vim-tmux-navigator#374]
I am using this tmux config

```bash
bind -r m resize-pane -Z
```

I typically have multiple tmux panes open at a time and switch between them using vim-tmux-navigator, but I don't want the plugin to take me out of the minimized mode and switch me to next pane when I press accdentaillly...

**Comment by christoomey** [comment]
Hi @shibisuriya - this is the default tmux behavior, and as discussed in a handful of previous issue (#56, #65, #133, #156, #152), I'm not inclined to alter the functionality here.
