### ISSUE TITLE
Default keybindings config from README did not work

### ISSUE THREAD

**Issue by DefinitelyNotSimon13** [christoomey/vim-tmux-navigator#375]
Hey there,

so I just installed the plugin and with the default config from the README the plugin did not work.

My setup:
- zsh 5.9
- tmux 3.3a
- nvim 0.9.5
- heavily modified version of nvchad with lazy package manager

I fixed it by simply adding the keybings myself

`M.vimTmuxNavigator = {
  plugin = true,
  n = {
    ["<C-h>"] = {
      "<cmd>TmuxNavigateLeft<CR>",
      "Navigate Tmux"
    },
    ["<C-j>"] = {
      "<cmd>TmuxNavigateDown<CR>",
      "Navigate Tmux"
    },
    ["<C-k>"] = {
      "<cmd>TmuxNavigateUp<CR>",
      "Navigate Tmux"
    },
    ["<C-l>"] = {
      "<cmd>TmuxNavigateRight<CR>",
      "Navigate Tmux"
    },
  }
}
`

It is very possible, that there simply was a clash in my config, just thought I'd add it as an issue, if anyone else encounters it!

**Comment by christoomey** [comment]
Hey @DefinitelyNotSimon13 - did you see the [`lazy.nvim` install instructions](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#lazynvim), and does it look like those would have worked for you here?

I've yet to make the full jump to nvim so not 100% sure the details, but it looks like that _should_ have covered things. I'm going to close this now as I believe we're set on this front, but wanted to highlight / confirm.

**Comment by DefinitelyNotSimon13** [comment]
@christoomey 
Yes, I was unable to get those to work!
I am also quite new to nvim, as such the error could very well be on my, however since the setup was working without any problems, when I just added the commands with "normal" keybinds, I just thought I'd mention it ^^
