### ISSUE TITLE
[feature request] support for :only

### ISSUE THREAD

**Issue by karshPrime** [christoomey/vim-tmux-navigator#384]
To have a keybind (or a command) to close all other panels other than the one selected irrespective of whether they're vim or tmux panels. Basically vim's `:only` functionality with tmux integration.

**Comment by christoomey** [comment]
Hey @karshPrime - appreciate the thought, but I try to keep the functionality here as focused as possible so not looking to add additional commands / features.

**Comment by karshPrime** [comment]
To anyone else in the future with a similar question, I've written a basic plugin to achieve this: [only-tmux.nvim](https://github.com/karshPrime/only-tmux.nvim).
