### ISSUE TITLE
Conflict with <C-j> and <C-k> keybindings in insert and select modes

### ISSUE THREAD

**Issue by MohammadLashkari** [christoomey/vim-tmux-navigator#388]
I have keymaps for <C-j> and <C-k> to jump to the next and previous snippet parameters in insert and select modes. However, I discovered a conflict with these keybindings when I checked your plugin's keybindings. I realized that these keybindings work in all modes by default. What is the reason for this, and wouldn't it be better if they only worked in normal mode to avoid such conflicts?

**Comment by christoomey** [comment]
Hmm, good point! These really should be normal mode only. I'd welcome a PR to update, and you can use the notes in [this section](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#custom-key-bindings) to redefine the key bindings to use normal mode mappings.
