### ISSUE TITLE
How are you dealing with the key binding conflict of Ctrl-k and kill-line in shells?

### ISSUE THREAD

**Issue by asmod3us** [christoomey/vim-tmux-navigator#389]
Not an issue, more of a usage question.

My muscle memory for `Ctrl-k` is tied to its behaviour in bash/zsh: kill-line. How are others using it with vim-tmux-navigator? Remapping keys (which ones and to what)?

**Comment by christoomey** [comment]
[There's a section in the README on restoring `C-l` for clear screen](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#restoring-clear-screen-c-l), but the same approach would apply for the other key bindings. You can also change the mappings if you'd like pre [this configuration section of the README](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#custom-key-bindings).

Closing this now as this isn't an issue and hopefully the above notes provide enough options for you.

**Comment by asmod3us** [comment]
Thanks for the pointer, the hard question is what key or set of keys to use as an alternative 😄 
Maybe other users can comment on what works for them?

As a side note, is detecting the position of the shell's cursor possible? To decide for either kill-line or move-up action?

**Comment by teatwig** [comment]
I just tried it out and was super impressed with how seamlessly everything works, until I had to press Ctrl-k for the first time and kill-line didn't work 😅
Maybe the easiest thing for now would be to do what @christoomey suggested so I at least have the option until I come up with something better.

I also thought about the "detecting the cursor position" thing a bit but I think I'd just lead to issues when you want to switch panes while in the middle of a line (to quickly copy something from somewhere else and insert it at this position).
