### ISSUE TITLE
Moving in vim (cygwin/zsh)

### ISSUE THREAD

**Issue by m42e** [christoomey/vim-tmux-navigator#39]
Well, I'd the same experience as decribed in #15, but as the ticket is a bit older I'd like to start a new one. 

I'm using tmux/vim in cygwin zsh but it fails in exactly the same way. I've tried the workarrounds with the extra shell script but I didn't get a proper result.

If i call the 

```
display-message -p '#{pane_current_command}'
```

from the tmux command line it always shows me 

```
zsh
```

there is no vim showing up. Even if I run the command from vims command line.

**Comment by Glennular** [comment]
I have the same issue with zsh/cygwin.  I used the following workaround to update the tmux-title on each zsh command. (https://bbs.archlinux.org/viewtopic.php?id=144149)

~/.zshrc

    case $TERM in
	  screen*)
		precmd(){
			# Restore tmux-title to 'zsh'
			printf "\033kzsh\033\\"
			# Restore urxvt-title to 'zsh'
			print -Pn "\e]2;zsh:%~\a"
		}
		preexec(){
			# set tmux-title to running program
			printf "\033k$(echo "$1" | cut -d" " -f1)\033\\"
			# set urxvt-title to running program
			print -Pn "\e]2;zsh:$(echo "$1" | cut -d" " -f1)\a"
                }
                ;;
    esac

**Comment by jackrh** [comment]
I just set up a cygwin/zsh/tmux/vim environment for the first time and it works great minus this issue.
 new-window vim works for me as well, but I couldn't get the case $TERM solution above to work.

**Comment by m42e** [comment]
Works for me

**Comment by m42e** [comment]
@christoomey Can we add this to the documentation maybe under "Known Limitations" or "FAQ"?

**Comment by m42e** [comment]
Hmm, I have to mention it does not work in a way I expected it to work. It shows vim in the pane, but only if I split the window before starting vim, which is not my general use.

**Comment by m42e** [comment]
Works with original configuration and current tmux trunk for me.

**Comment by jackrh** [comment]
Oh nice, tmux trunk works for me as well with the original configuration, thanks for sharing!
