### ISSUE TITLE
navigation in tmux zoom mode

### ISSUE THREAD

**Issue by MohammadLashkari** [christoomey/vim-tmux-navigator#398]
Hi, I noticed that when I'm in tmux zoom mode and only one pane is showing, if I press a navigation keybinding, it will exit zoom mode and navigate to another pane.

Wouldn't it be better if navigation keybindings didn't work in zoom mode? 

( I searched a bit and found this command to check if tmux is in zoom mode ` tmux display-message -p "#{window_zoomed_flag}" `  )

**Comment by christoomey** [comment]
I don't use this functionality myself, but I believe the [Disable While Zoomed](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#disable-while-zoomed) config option should cover what you need.

Closing this now under the assumption that that will cover what you're asking, but please feel free to comment or reopen if you think I missed something.

**Comment by MohammadLashkari** [comment]
Thanks `let g:tmux_navigator_disable_when_zoomed = 1` works great when there are multiple panes and you're in a zoomed Neovim pane. However, if you're in zoomed non-Neovim pane and navigate to another pane, tmux will exit zoomed mode. I tested this and it seems to be normal tmux behavior, unrelated to the plugin
