### ISSUE TITLE
nvim => tmux not working: "zsh:1: command not found: tmux"

### ISSUE THREAD

**Issue by j-krl** [christoomey/vim-tmux-navigator#399]
Followed the troubleshooting guide. I am on macOS 14.5. The output of `TmuxNavigatorProcessList` for me is `zsh:1: command not found: tmux`. Have messed with some of the shell settings on nvim and tmux to no avail and out of ideas. I am guessing it's related to the shell because `tmux` is certainly a command and installed.

Any ideas?

**Comment by imujtaba8488** [comment]
Same for me ... it works on Mac M1 pro but doesn't work on Mac M3 max (not sure if that's relevant)

**Comment by kbr-** [comment]
This uses the `system()` vim command to execute `tmux`. It could be that vim is running in some kind of sandbox and does no have access to / doesn't see `tmux`. I encountered this when running vim from flatpak (`flatpak run org.vim.Vim`):
```
/bin/sh: line 1: tmux: command not found
```
for vim installed from `apt` (I'm using Pop OS) it works.

**Comment by imujtaba8488** [comment]
Okay so for me, it turned out to be the .zshenv file. I entirely deleted it and everything is back to normal.

**Comment by christoomey** [comment]
I believe the issues here are unrelated the plugin -- if `tmux: command not found` then as noted, it sounds like an issue with vim, the shell vim uses (note, it might be different from your normal terminal shell -- see [this thread](https://superuser.com/questions/287994/how-to-specify-shell-for-vim) for notes), and the `$PATH` configuration for where to find `tmux`.

I'm going to close this now based on those notes, but please feel free to comment or reopen if you think I'm missing something.
