### ISSUE TITLE
TPM plugin overrides key binding for `<prefix> C-l`

### ISSUE THREAD

**Issue by x3rAx** [christoomey/vim-tmux-navigator#410]
When the plugins are loaded at the end of the `tmux.conf` ([as one should do](https://github.com/tmux-plugins/tpm/blob/99469c4a9b1ccf77fade25842dc7bafbc8ce9946/README.md?plain=1#L35-L36)), this plugin overrides the `<prefix> C-l` mapping:

https://github.com/christoomey/vim-tmux-navigator/blob/a9b52e7d36114d40350099f254b5f299a35df978/vim-tmux-navigator.tmux#L44-L45

**Comment by ghosert** [comment]
This is the biggest mistake in the history of this plugin, could you please merge this as soon as possible, I spent a few hours checking zsh/terminal/os/tmux/configurations, and finally see this bug.
