### ISSUE TITLE
<C-\>

### ISSUE THREAD

**Issue by Hope2KZ** [christoomey/vim-tmux-navigator#414]
how to close <C-\>
use toggleterm and vim-tmux-navigator 
i dont need dotoprevieious window how close it?

**Comment by christoomey** [comment]
There's a handful of notes in the README about customizing the keybindings -- see [this section on TPM installation](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#tpm) (if not using TPM you can just remove the keybinding from your tmux.conf) and [this section on configuring the vim keybindings](https://github.com/christoomey/vim-tmux-navigator?tab=readme-ov-file#custom-key-bindings) as examples
