### ISSUE TITLE
nvim navigate does not work under tmux

### ISSUE THREAD

**Issue by liberiulx** [christoomey/vim-tmux-navigator#415]
**The nvim pane navigation thru Ctrl + h/l/j/k does not work if opened a file under tmux. But it works without tmux. And tmux pane navigation works well thru Ctrl + h/l/j/k.**

**tmux version:**
❯ tmux -V
tmux 3.5a

**nvim version:**
❯ v -version
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189

**The output of TmuxNavigatorProcessList:**
S bash
S v

**My lazy.nvim plugin config:**
{
      "christoomey/vim-tmux-navigator",
        lazy = false,
      cmd = {
        "TmuxNavigateLeft",
        "TmuxNavigateDown",
        "TmuxNavigateUp",
        "TmuxNavigateRight",
        "TmuxNavigatePrevious",
      },
      keys = {
        { "<c-h>", "<cmd><C-U>TmuxNavigateLeft<cr>" },
        { "<c-j>", "<cmd><C-U>TmuxNavigateDown<cr>" },
        { "<c-k>", "<cmd><C-U>TmuxNavigateUp<cr>" },
        { "<c-l>", "<cmd><C-U>TmuxNavigateRight<cr>" },
        { "<c-\\>", "<cmd><C-U>TmuxNavigatePrevious<cr>" },
      },

**My tmux config:**
set -g @plugin 'christoomey/vim-tmux-navigator'

**Comment by christoomey** [comment]
It looks like your process list has `v` for the vim entry. The plugin will not be able to detect that you're running vim as `v` with the default configuration. You'll need to update the regex used in the tmux config to match `v` -- I think the following should work.

``` diff
  is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
-     | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
+     | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf|v)(diff)?$'"
```

Hopefully the above fixes things or at least points you in the right direction. I'm going to close this issue now, but feel free to comment or reopen if you think there's actually something off with the plugin itself.

**Comment by liberiulx** [comment]
Thanks so much. You got it right.
