### ISSUE TITLE
A 3rd-party integration. e.g. seamless i3/tmux/vim

### ISSUE THREAD

**Issue by rafi** [christoomey/vim-tmux-navigator#45]
I've extended this idea and joined the window-manager I use, [i3](http://i3wm.org), to this navigation hook. Tmux's devs were nice to [include](http://sourceforge.net/p/tmux/tmux-code/ci/7160b8c2d5d17565ef8da0fb532cb49b2d5718bb/) new output messages that enables "edge" detection for tmux's panes.

The only thing is I had to change the `cmd` to:

``` viml
    let cmd = 'i3-focus ' . tr(a:direction, 'phjkl', 'lLDUR') . ' vim'
```

Instead of forking this, could you add the cmd as a global so it could be configured?
_e.g._

``` viml
    let g:tmux_navigator_cmd = 'i3-focus %s vim'
    "let g:tmux_navigator_cmd = 'tmux select-pane -%s'
```

**Comment by jck** [comment]
@rafi Is your i3-focus script available somewhere?
