### ISSUE TITLE
tmux-navigator breaks after re-sourcing ~/.vimrc

### ISSUE THREAD

**Issue by nargetdev** [christoomey/vim-tmux-navigator#46]
I'm a configuration junkie so I'm always modifying my ~/.vimrc
When I source ~/.vimrc during a session the seamless navigation breaks (I have to use my prefix again)
-Note that navigation works until then.

Has anybody bumped into this?

When I figure out what part of my .vimrc is the cause I will report back!

**Comment by nfarrar** [comment]
I just bumped into this issue. Not sure why it's happening.

**Comment by christoomey** [comment]
@nfarrar Did you try to debugging step listed above with `:verbose nmap <C-j>` after re-sourcing?

**Comment by nfarrar** [comment]
@christoomey Sorry, I didn't - and you were exactly right - that was the problem. I still had my mappings that setup window navigation from before I started using vim-tmux-navigator.
