### ISSUE TITLE
About Tmux zoom feature

### ISSUE THREAD

**Issue by oblitum** [christoomey/vim-tmux-navigator#56]
I'd like to put in discussion what would be the best behavior when you zoom a particular pane. For me it's a bit annoying when I'm in a zoomed pane and get out of zoom by accident when moving around buffers/panes.

Would it be possible/desirable to have vim-tmux-navigation  disabled (both for tmux as for vim) when zoom is ON in a given pane? Because I find vim-tmux-navigation useful solely when zoom is off.

**Comment by oblitum** [comment]
Just wanted to report here that, form some reason, recently on Archlinux with an up to date tmux and vim-tmux-navigator, the plugin is behaving the way I wished. I'm forced to zoom out to tmux-navigate.

**Comment by blueyed** [comment]
See #133 for a fresh approach at this.

**Comment by oblitum** [comment]
@blueyed thanks for letting me know... current behaviour for me is back as formerly explained in the issue, it seems I've learned to live with it, but if you got a fix I'll sure switch, I don't like the default.

**Comment by blueyed** [comment]
Yeah, try #133.  It even let's you zoom out on 2nd invocation by default.
I think that's what @christoomey could live with even - but there's also a setting to get the current behavior.

**Comment by oblitum** [comment]
Just trying.
