### ISSUE TITLE
renders off by one line when using syntastic?

### ISSUE THREAD

**Issue by chevett** [christoomey/vim-tmux-navigator#57]
This is a sane plugin for an insane world!  Great stuff!

If vim is in my top pane, I have syntastic active mode enabled, do a quick :w and C-j, then vim starts to render everything off by one line.

before
---------
![image](https://cloud.githubusercontent.com/assets/1141615/5710309/077c756c-9a6f-11e4-85ed-26ec97f1491b.png)

after :w and switching panes immediately.
--------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/1141615/5710326/2dce484e-9a6f-11e4-9988-3d26dffea3b9.png)

if i keep doing this, then it keeps getting worse.
after after
-------------
![image](https://cloud.githubusercontent.com/assets/1141615/5710372/7b359be6-9a6f-11e4-9ef7-508abace6983.png)

If i resize the pane, then everything goes back to normal.  I know that syntastic performs a syntax check when I do a :w, and disabling syntastic fixes the problem.  Any ideas?  Thanks!

**Comment by christoomey** [comment]
Hello @chevett, thanks for the kind words.

Unfortunately I don't know if there is much I can do to prevent the issue. Syntastic is blocking after the write and Vim mis-handles your action and adds the lines. Not specifically `tmux-navigator` related, the same sort of thing would happen if you hit `j` or `k` to navigate while Syntastic was blocking (specifically, `j` or `k` artifacts would remain in the command line after the write completed)

That said, you can run the command `:redraw!` to clear up the UI when these sort of things pop up. Hope that helps.

Closing this, but please reopen or comment if you think there is something to `tmux-navigator` going on here.

**Comment by chevett** [comment]
Would you expect this to be fixed if syntastic did a `:redraw!` after performing it's check?

**Comment by christoomey** [comment]
Could be. You could put syntastic into "Passive mode" then create a mapping that ran syntastic and did the `redraw!`.

**Comment by chevett** [comment]
oh good call!  I'll give that a try.  Thanks a lot.

**Comment by jdivock** [comment]
+1 seeing this as well, I'll try the redraw but hopefully some one can come up with a better solution.

**Comment by adamgotterer** [comment]
Having the same problem. @chevett did you ever find a reasonable solution?

**Comment by chevett** [comment]
I tried and gave up.  This is still pretty rough for me.

**Comment by brentburg** [comment]
I was having this same issue. This fixed it for me:

```
:au BufWritePost * redraw!
```

**Comment by chevett** [comment]
@brentburg, you have had a meaningful and positive impact on my life.  this worked for me!  thanks!

**Comment by brentburg** [comment]
@chevett, no problem, I am glad it helped!

**Comment by felix-d** [comment]
@brentburg it seems it's not called exactly at the right moment, I have a buffer that takes time to be checked by syntastic and the issue still occurs.

**Comment by adamgotterer** [comment]
I found switching to neovim fixed the problem for me.

**Comment by dhinus** [comment]
Same problem here, the workaround suggested by @brentburg definitely helps. There's a related thread in the Syntastic repo with more suggestions: https://github.com/scrooloose/syntastic/issues/822
