### ISSUE TITLE
Doesn't work well with vim-session

### ISSUE THREAD

**Issue by simendsjo** [christoomey/vim-tmux-navigator#58]
If I open vim, it works fine, but if I open using `OpenSession sessionname` it doesn't work anymore.
The strange thing is that `:TmuxNavigateLeft` and similar works, but the keybindings doesn't work anymore. Rebinding the key doesn't work either.

**Comment by christoomey** [comment]
Hello @simendsjo, can you clarify what `OpenSession` is? Is that run from the shell?

Likely the case is that the current_process name in tmux is not Vim. You can confirm this by running `:TmuxPaneCurrentCommand` in Vim. If the output is not `Vim` or something pretty close, there is not much we can do unfortunately.

**Comment by simendsjo** [comment]
Ah, I see the problem. I'm actually starting vim through make and not directly. This makes `:TmuxPaneCurrentCommand` say `make`... Need to think of a way around this..

**Comment by christoomey** [comment]
@simendsjo Figured that was the case. I'm going to close this now as there is not much I can do on my side, but hopefully you can sort things on your end. Please comment or reopen if it seems like there is something I'm missing.

**Comment by simendsjo** [comment]
I just added make to the grep in `.tmux.conf`. A really ugly and hackish solution, but I don't think it will break on my setup. Thanks for your help.
