### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by wikimatze** [christoomey/vim-tmux-navigator#60]
Would it be possible to have a final release of your plugin with a git tag? I don't always want to grab updates from master.

Thanks for this awesome plugin.

**Comment by christoomey** [comment]
Hello @wikimatze, thanks for the note. I've just tagged [v1.0](https://github.com/christoomey/vim-tmux-navigator/releases/tag/v1.0) as I feel like things are pretty stable right now.

**Comment by wikimatze** [comment]
Trying it out and it works very stable, thanks for the fast answer.
