### ISSUE TITLE
Keymappings fail in Neovim

### ISSUE THREAD

**Issue by benmccormick** [christoomey/vim-tmux-navigator#61]
I'm trying out Neovim, and having issues with tmux-navigator in that environment. Calling `:TmuxNavigate` commands directly works fine, the key mappings seem to fail.  My vimrc works fine in the Vanilla OSX vim and mvim, but fails in Neovim.  

Remapping to a different combination works, but <ctrl-hjkl> all fail.

I was worried about conflicts, so I ran this simplified .vimrc and it still fails:

```
set nocompatible

set shell=bash
set shellpipe=2>/dev/null>
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()
Plugin 'gmarik/vundle'

"Integrate with tmux
Plugin 'christoomey/vim-tmux-navigator'

"End Vundle
call vundle#end()
" "Vundle ended so reenable filetypes
filetype plugin indent on
```

Any ideas what might be causing this?

This is nvim version: NVIM 0.0.0-alpha+201501221728
Tmux Version: 1.8

Corresponding Neovim issue here: https://github.com/neovim/neovim/issues/1868

**Comment by christoomey** [comment]
Hello @benmccormick, thanks for reporting this. Just tested locally in neovim and navigation works as expected so my guess is that your tmux.conf are not recognizing when (n)Vim is active. Do the key-bindings just treat the Vim pane as a single Tmux pane, ignoring the Vim splits?

Can you check you tmux conf key-binding settings and update to [the latest key-binding config](https://github.com/christoomey/vim-tmux-navigator#tmux) if that is not what you have?

**Comment by benmccormick** [comment]
@christoomey 

> Do the key-bindings just treat the Vim pane as a single Tmux pane, ignoring the Vim splits?

That's the effect, but after more exploration, this definitely seems to be an issue with the build of Neovim I'm on, not your issue in any way.  I can't assign anything to a <ctrl-*> keybinding and have it work.  When I remap the tmux commands to <leader>* they work fine.  I've opened up a neovim issue, and will try to figure it out from that end.

Thanks for the quick reply!

**Comment by benmccormick** [comment]
On second thought...

Next time I should read **before** I assume I've already figured out the problem.  Updating the key-binding seems to have fixed it.  

Even more thanks.

**Comment by christoomey** [comment]
:+1:

**Comment by gbonfant** [comment]
Hey, 

Sorry to reopen this conversation but I'm also experiencing some issues with neovim. On my case however all the mappings work with the exception of `C-h` inside neovim, in other words: when pressing `C-h` from a neovim split on the right, the navigation doesn't occur and instead the cursor is moved one character to the left.

I have no mappings on vim for that key combination. Any ideas what might be causing this behaviour?

Thanks!

**Comment by christoomey** [comment]
Just to confirm, can you reply with the output of the following (run in vim):

``` vim
:verbose nmap <C-h>
```

Expected output is:

```
n  <C-H>       * :TmuxNavigateLeft<CR>
        Last set from ~/code/vim/tmux-navigator/plugin/tmux_navigator.vim
```

**Comment by gbonfant** [comment]
Hey @christoomey, thanks for getting back to me. I've got the same output (different path), here it is just in case:

```
n  <C-H>       * :TmuxNavigateLeft<CR>
        Last set from ~/.nvim/plugged/vim-tmux-navigator/plugin/tmux_navigator.vim
```

I've also tried reinstalling neovim with a minimum `.nvimrc` but I get the same issues. 

Sending the command to vim via `:TmuxNavigateLeft` seems to work, however `<C-h>` doesn't... I've made a [30s clip](https://dl.dropboxusercontent.com/u/7683822/tmux-navigator.mov)  that might help visualise the issue.

**Comment by christoomey** [comment]
Hmmm, this is interesting. The command works, and the mapping clearly points at the command, but the mapping doesn't have the expected behavior. At this point we are down to checking the crazy things, since the sane things all check out.

The two things I would look into are:

1. Is there any mapping in either tmux or your terminal application the is capturing `<C-h>` keystrokes? (`tmux list-keys | grep 'C-h'` will narrow the search in tmux)
2. Is your nvim build not responding correctly to `execute 'wincmd ' . a:direction` where `direction` is "h"

There are a couple of other layers to the Vim plugin that we could explore, but I would start with those.

**Comment by gbonfant** [comment]
I've tried running everything with a bare `tmux.conf` (only having the bindings for vim-tmux-navigator) and that didn't seem to help – My tmux configuration is nothing out of the normal but [here's a link](https://github.com/gbonfant/dotfiles/blob/master/.tmux.conf)  in case you might want to take a quick look.

1. I get this after piping to grep:
```
bind-key -n     C-h if-shell "echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"" "send-keys C-h" "select-pane -L"
```

2. Weirdly enough `execute 'wincmd h'` and `let direction='h' execute 'wincmd ' . direction` work alright.

I'm starting to think the current build of neovim might be at fault.

**Comment by tristil** [comment]
For anyone else looking for a temporary solution to this, this worked for me. I didn't come up with it. It was given to me in the Neovim Gitter room.

```bash
infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
```

**Comment by gbonfant** [comment]
That's bizarre, did they mention why would you have to replace the mapping to `\177`? In any case, it did work! Thanks :)

**Comment by alexdunn** [comment]
Wow, this saved me!  What a hassle!

**Comment by niccnacc** [comment]
Could anyone please explain to me, where to put this to a non-IT guy? I read the article on SO, but I really have no clue where exactly this missinterpretation happens - the terminal, bash, tmux or whatever. Putting the two lines in tmux conf works, but triggers some command not found on each startup, which is really annoying, since I got scripts depending on it to start and take a command..
In bashrc it doesn't work at all.

**Comment by AndreiMotinga** [comment]
@tristil , Thank you
