### ISSUE TITLE
problems with installing vim-tmux-navigator

### ISSUE THREAD

**Issue by acandael** [christoomey/vim-tmux-navigator#66]
I installed Vundle and then added

Bundle 'christoomey/vim-tmux-navigator'
to my ./vimrc file

I added the new bindings to my .tmux.conf file:

    # Smart pane switching with awareness of vim splits
    is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
    bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
    bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
    bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
    bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
    bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

but when I source the .tmux.conf file, I get this error:

    /Users/acandael/.tmux.conf:8: invalid or unknown command: is_vim='echo "#{pane[0/0]│   1 set    nocompatible              " be iMproved, required
    /Users/acandael/.tmux.conf:9: invalid or unknown command: "(^|\/)g?(view|n?vim?)(d'

how can I fix this?

greetings,

Anthony

**Comment by christoomey** [comment]
What is your tmux version? I might be using tmux 1.9+ features. You can check with `tmux -V` in the shell.

**Comment by acandael** [comment]
Hi Chris, my bad, I didn't notice that copying the code had truncated the lines, which made the syntax invalid. It's working now and I can flawlessly navigate between tmux panes and vim panes.

**Comment by christoomey** [comment]
No worries and glad to see it's working for you! Closing now as it sounds like the issue has been resolved, but please reopen or comment if you continue to have any issues.
