### ISSUE TITLE
Annoying cryptic error message

### ISSUE THREAD

**Issue by oblitum** [christoomey/vim-tmux-navigator#67]
This message was showing quite frequently for me, I've just muted it. Any reason to leave it as is? The message kept showing and it's quite cryptic and didn't help at solving anything.

```diff
diff --git a/plugin/tmux_navigator.vim b/plugin/tmux_navigator.vim
index ef3ae93..c63ed58 100644
--- a/plugin/tmux_navigator.vim
+++ b/plugin/tmux_navigator.vim
@@ -68,7 +68,7 @@ function! s:VimNavigate(direction)
   try
     execute 'wincmd ' . a:direction
   catch
-    echohl ErrorMsg | echo 'E11: Invalid in command-line window; <CR> executes, CTRL-C quits: wincmd k' | echohl None
+    " echohl ErrorMsg | echo 'E11: Invalid in command-line window; <CR> executes, CTRL-C quits: wincmd k' | echohl None
   endtry
 endfunction
```

**Comment by av3r4ge** [comment]
It means that when you are in the command-line window, you can't use wincmd (or any other command to move or edit another buffer).
Here's a quote from the `:help command-line-window`:
>The command-line window is not a normal window.  It is not possible to move to
another window or edit another buffer.  All commands that would do this are
disabled in the command-line window.  Of course it _is_ possible to execute
any command that you entered in the command-line window.  Other text edits are
discarded when closing the window.

**Comment by oblitum** [comment]
@av3r4ge ah, thanks for clarification. It's strange, I'm on OS X now, and it doesn't show up, but on Linux it was, hence I've found it quite annoying since it was not my experience. I also can't say now for sure whether on Linux it was showing up out of the context you explained, I'll look it further later just to be sure.

**Comment by christoomey** [comment]
This message / functionality comes from Vim itself (although I am wrapping it in the plugin to provide a slightly more friendly error message). The idea, as far as I understand it is that the command line window is meant to act like a modal and block other interactions until you finish with it, and as such navigation commands are blocked.

I'm going to close this now as I don't think there is a problem with the plugin, but please reopen if you think there is something worth reviewing.
