### ISSUE TITLE
Hotkeys not working when vim is started from another process (e.g. git)

### ISSUE THREAD

**Issue by DeX3** [christoomey/vim-tmux-navigator#69]
Hello there,

fine work here. Only problem I've come across is that the hotkeys don't work if started from a different process. This is often the case in my workflow, for example when doing `git commit` or `git mergetool`. A quick & dirty fix would be to just change the line

    is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'

to

    is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)(git|g?(view|n?vim?)(diff))?$"'

in your `.tmux.conf` which is what I'm using right now, however this results in having the hotkeys active whenever git is the active command, and not just when vim has been started through git. I was wondering if you could come up with a better solution?

**Comment by christoomey** [comment]
Hey @DeX3,

Thanks for the kind words. I"ve encountered what you describe and unfortunately the only solution currently available is to keep adding conditions to the grep pattern to support more variants of process names. For the core functionality I am only comfortable including vim-like processes, so `git` doesn't quite make the cut.

I have yet to investigate fully, but I believe a more complete solution may be possible using the tmux environment as presented in [this PR](https://github.com/christoomey/vim-tmux-navigator/pull/37). I hope to look into this further in the future, but have yet to find the time.

I'm going to close this issue now as I think any work to be done is better captured by that PR, but please comment or reopen if you think there is a distinct issue with the plugin. Thanks.
