### ISSUE TITLE
Investigate vim wrapping

### ISSUE THREAD

**Issue by christoomey** [christoomey/vim-tmux-navigator#70]
http://www.reddit.com/r/vim/comments/22ixkq/navigate_around_vim_and_tmux_panes_painlessly/cgnnnai?context=2

**Comment by srsudar** [comment]
I'd love to see this! I disagree with that poster that it doesn't belong as a plugin. I like it as a plugin.

**Comment by blueyed** [comment]
@srsudar 
I think the idea is to integrate it into this plugin.
Would you like to give that a try?

**Comment by akkartik** [comment]
I'm the author of the original script in that reddit comment. Please feel free to submit a PR including it here (a link to the comment and/or http://akkartik.name would be appreciated).

The reason this isn't quite a classic package: there's some additional setup required to put the `tmux_navigate` somewhere in your path. So it can't just be a line in your vimrc or whatever.

**Comment by blueyed** [comment]
> `tmux_navigate` somewhere in your path

It could be used with the full path also, like I did initially in #117 when the script was too long.

**Comment by christoomey** [comment]
Possible that the TPM install (https://github.com/christoomey/vim-tmux-navigator/pull/123) could provide a more straightforward way to package / hook into the script needed for this?

**Comment by christoomey** [comment]
I'm going to close this now as I've not found the time to investigate this, realistically I haven't felt the pain of not having this, and I'm generally concerned about adding any more complexity to this little system we've built up here.

**Comment by srsudar** [comment]
Sounds good to me. I forgot about this altogether, which clearly means it's working well! I'm happy with my current setup, and I'm not going to re-read that link for fear of becoming dissatisfied...
