### ISSUE TITLE
Doesn't work when #{pane_current_command} is something unexpected (e.g., git)

### ISSUE THREAD

**Issue by clin18** [christoomey/vim-tmux-navigator#73]
Not really an issue, since I already have a solution. Just wanted to share.

Instead of
```
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
```
we could use
```
is_vim='tmux show-environment #{pane_id}_is_vim'
```
then the plugin could do something like
```
if exists('$TMUX')
    autocmd VimEnter * silent execute '!tmux set-environment ${TMUX_PANE}_is_vim true'
    autocmd VimLeavePre * silent execute '!tmux set-environment -u ${TMUX_PANE}_is_vim'
endif
```
This wouldn't work if you put vim in the background, but who does that, honestly?

**Comment by christoomey** [comment]
Hello @clin18, thanks for sharing. This is a consistent bit of feedback difficulty with the plugin but I've yet to get to a final solution. @blueyed has introduced a potential implementation using the environment as you mention: https://github.com/christoomey/vim-tmux-navigator/pull/37. I'm interested in pursuing these but have not had time as of late. Closing this as I believe the PR I mentioned better covers this topic, but please feel free to comment or reopen if you have any questions.
