### ISSUE TITLE
markdown not displaying correctly on project page

### ISSUE THREAD

**Issue by zaqthefreshman** [christoomey/vim-tmux-navigator#76]
On https://github.com/christoomey/vim-tmux-navigator your markdown is being displayed as raw text. This is likely due to the README have a .mk extension instead of .md or one of the other valid extensions. (https://guides.github.com/features/mastering-markdown/)

**Comment by christoomey** [comment]
Woops! Thanks for pointing that out. Fixed in 176452ead44118174ddad3502709a247d9c24bb4
