### ISSUE TITLE
Switching from vim to non vim tmux split is delayed

### ISSUE THREAD

**Issue by krzkrzkrz** [christoomey/vim-tmux-navigator#79]
Not sure if this is related:

https://github.com/christoomey/vim-tmux-navigator#switching-out-of-vim-is-slow

Is there a workaround for the Fish shell?

**Comment by christoomey** [comment]
Hello @krzkrzkrz, my guess is it is related to your shell's startup time (which is discussed in the link you included). Check out https://github.com/christoomey/vim-tmux-navigator/issues/72 for more detail.

**Comment by krzkrzkrz** [comment]
Great, I've replied on that thread, with more details. Closing this one.
