### ISSUE TITLE
Sending redraw, c-k conflict.

### ISSUE THREAD

**Issue by breerly** [christoomey/vim-tmux-navigator#80]
How do you suggest sending C-K when it is overridden by this plugin?

**Comment by christoomey** [comment]
Hello @breerly, I cover this indirectly in the readme in the section on [Restoring Clear Screen (C-l)](https://github.com/christoomey/vim-tmux-navigator#restoring-clear-screen-c-l).

The best solution I've found is to configure the given key mapping to work with the prefix key, so `C-s` then `C-k` would send `C-k`.

``` tmux
bind C-k send-keys 'C-k'
```
