### ISSUE TITLE
Broken in Tmux 2.1

### ISSUE THREAD

**Issue by adambiggs** [christoomey/vim-tmux-navigator#84]
I just tried compiling Tmux from the latest master branch (v2.1), and found that I can no longer navigate between Vim panes.

The problem is that `is_vim` in the following line is now always false:

```tmux
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
```

Unfortunately, after some digging I found that in Tmux 2.1 `#{pane_current_command}` returns `zsh` instead of `vim`...

Hopefully there's some other method to tell if Vim is active in a Tmux pane.

**Comment by adambiggs** [comment]
Nevermind, [sounds like](https://github.com/tmux/tmux/issues/108#issuecomment-146675485) this has to do with a Tmux patch I applied trying to fix a different issue.

**Comment by christoomey** [comment]
Glad to know this is sorted out! Thanks for reporting and following up.
