### ISSUE TITLE
TmuxPaneCurrentCommand returns "sh" 

### ISSUE THREAD

**Issue by infokiller** [christoomey/vim-tmux-navigator#85]
I'm using VIM 7.4, Ubuntu 14.04 and Tmux 2.0.
Not working because of this (tmux doesnt recognize that vim is running).

**Comment by christoomey** [comment]
Hi @infokiller, can you provide any additional detail? Specifically, 

- What does `which vim` return?
- How are you opening vim? (assuming you just run `vim`, but want to confirm).

I've not see this particular problem, but hoping the above might clarify

**Comment by infokiller** [comment]
Hi @christoomey and thanks a lot for your response.
I just tested it on another computer with very similar configuration (my dotfiles and some of the packages are synced) and the command worked well. I'll check it again on my laptop when I get home and report back.

**Comment by infokiller** [comment]
OK I think I understand what's happening now- this only happens when I'm opening vim with fasd (same as the other issue). I'll merge this one into the other one.
