### ISSUE TITLE
Vim split not detected when file edited with fasd alias

### ISSUE THREAD

**Issue by chenoweth** [christoomey/vim-tmux-navigator#86]
Hello,

thank you for this vim plugin, it works great.

I've just a little problem. I'm often using [fasd](https://github.com/clvv/fasd).

Among other things it allows me to create an alias called `v` defined in my ~/.zsh_aliases : 
```
alias v='f -t -e vim -b viminfo'
```
If I type `v foo`, fasd will search the most "[frecent](https://en.wikipedia.org/wiki/Frecency)" file containing the chain foo in its path and open it with vim.

Inside vim, if I open a split with the `:sp` command and try to switch to it with the keybindings offered by vim-tmux-navigator, tmux complains in the status bar with the message :
>Pane not found

If I close the file and reopen it with vim, but this time directly with the full command `vim /path/to/foo`, the split is then correctly detected.

If I type `v foo` outside of tmux, the keybindings work fine.

So I may be wrong, but it seems to me that the plugin doesn't detect the split and as a consequence forwards the operation to tmux which complains that there are no other panes in the given direction.

I would like the split to be detected even when I call vim through fasd inside tmux.
Is there any simple workaround to this problem ?

I'm using [vim version 7.4](https://gist.github.com/chenoweth/5e6777c03f93eccce4f3) on xubuntu 14.04.3, and tmux version 2.0 installed from this [ppa](https://launchpad.net/~pi-rho/+archive/ubuntu/dev).

`which vim` returns `/usr/bin/vim`.

Thank you for your help.

**Comment by infokiller** [comment]
Duplicate of #85

**Comment by chenoweth** [comment]
Ok, so I think I understand a little better.

The problem seems to come from ~/.tmux.conf.
The line : 

>is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'

... tests whether vim is running inside the current pane.

If vim is called directly, the test is able to detect it, however if it's called through a shell script wrapper like fasd, the test fails to detect vim, because when I send the following command to tmux : 

>display -p '#{pane_current_command}'

... it displays `vim` when vim is called directly, but `sh` when called through fasd.

The problem is : 
When vim is a child of the `#{pane_current_command}` process, how to detect it ?
It should be possible to find the process pid with tmux variable #{pane_pid}, then find its children and check whether one of them is vim...
But then I wonder if there could be situations where the pane process would have vim as one of its child, without vim being displayed on the pane (maybe another child or the pane process itself).

I don't know if this issue can be fixed.

Anyway, it seems that this issue is a duplicate of #15 so I suppose I should close it.

PS : 

For people using fasd + zsh and who don't already know it : 
to edit a file quicker without typing its full path, you can type `v foo`, but you can also type `vim ,foo` then by pressing `tab` you have access to an interactive menu in which you can select your most frecent files.
It's 3 more keys to press but still better than typing a full long path, and with this method the vim splits are correctly detected.

For this to work you have to enable a word completion mode by passing some arguments (zsh-wcomp zsh-wcomp-install) to fasd when you initialize it in your zsh config file.
In case it helps, here's what I've got in my zshrc : 

>fasd_cache="$HOME/.fasd-init-zsh"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache
