### ISSUE TITLE
<Ctrl-L> conflicts with clear screen

### ISSUE THREAD

**Issue by vysakh0** [christoomey/vim-tmux-navigator#9]
Ctrl-L does not seem to work in my shell in  a tmux session, is there a neat workaround?

**Comment by gyermolenko** [comment]
Since I misunderstood README and lost a bit of time figuring this out, I want to clarify what can be done to restore <C-l> behavior.

1. If you use tpm, put restoring bind **after** calling package manager: 
```
run '~/.tmux/plugins/tpm/tpm'
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "send-keys C-l"
```
(if you don't use tpm - just do not put "bind-key -n C-l" line in config)

2. Do this part of README in vimrc (also wo C-l line)
```
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <C-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-j> :TmuxNavigateDown<cr>
nnoremap <silent> <C-k> :TmuxNavigateUp<cr>
```

**Comment by blueyed** [comment]
@gyermolenko 
You might want to create a PR to improve the documentation!

**Comment by yugawara** [comment]
I use neovim + tmux + tpm.
After
```
run '~/.tmux/plugins/tpm/tpm'
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "send-keys C-l"
```
I was able to use CTRL + ALT + L to clear the screen

**Comment by tonyma** [comment]
Hi @yugawara , how did you map ctrl + alt + l to clear screen? it doesn't work for me, I am on Mac.

here is my tmux config:
`
bind -n C-M-l send-keys clear
`

**Comment by psaikido** [comment]
Hi @tonyma and anyone else looking at this issue, here's one solution. Leave the tmux config alone so that Ctrl+l goes left and instead use Ctrl + Alt + L to clear the screen. In bashrc:
bind -m vi-command 'Control-Alt-l: clear-screen'
bind -m vi-insert 'Control-Alt-l: clear-screen'

**Comment by Act0r1** [comment]
> @vysakh0, no worries and thanks for clarifying.
> 
> The fact that `<Ctrl-L>` will no longer do clear screen is expected behavior. The tmux mapping takes precedence.
> 
> There are two solutions for this problem. I have just added a [section to the project README](https://github.com/christoomey/vim-tmux-navigator#restoring-clear-screen-key-binding) to describe the solutions.
> 
> Personally, I use the remapping option by adding `bind C-l send-keys 'C-l'` which lets me use `<prefix>-l` to clear the screen, but alternately you can use different mappings for the navigation mappings to avoid the conflict.
> 
> Hope that helps!

I'm using right now this config ->bind -n C-l send-keys 'C-l', but it doesn't work, can use like in usual terminal only C-l without any prefix there ?

**Comment by owenstake** [comment]
In my situation, `export TERM=xterm` solve my problem in centos7 in tmux3.2a. Tmux 3.2a default TERM is `tmux-256color`, it can not interpret key `ctrl+L` correctly in centos7.

**Comment by rendivs925** [comment]
> Hi [@yugawara](https://github.com/yugawara) , how did you map ctrl + alt + l to clear screen? it doesn't work for me, I am on Mac.
> 
> here is my tmux config: `bind -n C-M-l send-keys clear`

Nice it works, but it did not automatically enter, so here is the solution
```
bind -n C-M-l send-keys 'clear' C-m
```
