### ISSUE TITLE
Feature request: take advantage of select-pane -P to color panes and buffers

### ISSUE THREAD

**Issue by sagotsky** [christoomey/vim-tmux-navigator#91]
According to http://siadat.github.io/tmux-pane-style/, tmux 2.1 lets you style individual panes.  I'd love to see this plugin let me set an active pane color and set either the tmux pane or the vim buffer I'm in accordingly.  I've been using vim-diminactive to color vim buffers, but it doesn't work when I've got a zsh pane adjacent to vim.

**Comment by blueyed** [comment]
I think that's out of scope for this plugin.

Just configure it for tmux.

I am using this with base16-solarized:

For dark:

```tmux
if '[ "#{pid}" ]' '\
  setw -g window-style "bg=colour18" ;\
  setw -g window-active-style "bg=black"'
```

For light:

```
if '[ "#{pid}" ]' '\
  setw -g window-style "bg=colour21" ;\
  setw -g window-active-style "bg=brightwhite"'
```

The `if` is to detect tmux 2.1.

Cheers for using (and mentioning) vim-dimactive.. ;)

Closing this.  Please re-open in case I'm missing something, but I don't think this plugin should mess with window settings, especially when there's an `active` variant already.

(The link (http://siadat.github.io/tmux-pane-style/) returns an empty page btw)
