### ISSUE TITLE
Can't use <C-w> for window navigation?

### ISSUE THREAD

**Issue by ZzAntares** [christoomey/vim-tmux-navigator#93]
Personally I don't want to use `<C-h>`, `<C-j>`, `<C-k>` and `<C-l>` for window navigation, I prefer such mappings for buffer and tab navigation in vim, I'm happy to use `<C-w>` prefix for window navigation, I'tried to map this in `.tmux.conf` but seems tmux can not handle mappings of two keystrokes.

The only thing I could do is set my tmux prefix to `<C-w>` and use this mappings:

```viml
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
bind h if-shell "$is_vim" "send-keys h" "select-pane -L"
bind j if-shell "$is_vim" "send-keys j" "select-pane -D"
bind k if-shell "$is_vim" "send-keys k" "select-pane -U"
bind l if-shell "$is_vim" "send-keys l" "select-pane -R"
```

This will work perfect on the tmux side, but when jumping into a tmux pane (where vim is) now I can't get out since if I type `<C-w>h` or any other navigation command nothing happens, (typing the `:TmuxNavigateXXX` works fine).

How can I get this to work?

Thanks

**Comment by christoomey** [comment]
Hello @ZzAntares, I'd recommend against using `C-w` as your prefix as `C-w` is a useful readline key binding for delete word.

That said, if you're set on it, you'll need to update the tmux mappings a bit further. Specifically, you'll need to change the `send-keys` portion so that it sends `C-w h`, rather than just h.

**Comment by ZzAntares** [comment]
Thanks! I made it work, but now that you mention it, you're right is a little bit annoying to type `C-w` twice to delete the word, so I'm very tempted to use the default mappings, but that makes me wonder, what do you use for buffer navigation within vim? pure `:b` commands?

Thanks.

**Comment by christoomey** [comment]
Hi @ZzAntares, glad I could help. I'm not sure I understand your other question though. When you say "buffer" navigation, do you mean moving between splits in a Vim window? If so, that's the magic of this plugin, it dynamically determines if you are trying to navigate between Vim splits or tmux panes and does the right thing.

If I am misunderstanding you, could you clarify what you are asking?

**Comment by ZzAntares** [comment]
Hi, sure @christoomey, I understand what this plugin does, it lets me jump between tmux panes and vim panes as if it were the same, however since I use `<C-h>` for `:bprevious` and `<C-l>` for `:bnext` in vim, then I can not use this plugin defaults, that was I was asking to use `<C-w>` for window/pane movement, since you're right and using `<C-w>` twice to delete a word is annoying, I was wondering, what vim mappings do you use (I'm just curious) for navigating between vim buffers (not windows/panes, not tabs)?

Thanks

**Comment by christoomey** [comment]
Hi @ZzAntares, I am still not quite sure what you mean / think there might be a nomenclature disconnect. To clarify, from the Vim help:

> Summary:
>    A buffer is the in-memory text of a file.
>    A window is a viewport on a buffer.
>    A tab page is a collection of windows.

So when you ask "what mappings do you use for navigating between vim buffers", I assume you mean windows, aka splits, in Vim world. Via this plugin, I use `C-j`, `C-k`, etc for both Vim window/split/buffer (all the same thing) navigation, as well as navigation between tmux splits.

The only other level in vim is a tab page, which I navigate using the default `gt` and `gT` navigation.

Please let me know if I am still misunderstanding you, but hopefully this clarifies.

**Comment by ZzAntares** [comment]
Yes I mean, when you use `:e somefile.txt`, you're opening a vim buffer, if you edit another file `:e otherfile.txt` then you're opening a second buffer, one can navigate through buffers with `:bnext` and `:bprevious`, windows in the other hand are splits which are not related to buffers (kind of), navigating windows is through `<C-w>` and some key you already know (`hjkl`), and finally tabs are a collection of windows, here is a better explanation http://blog.sanctum.geek.nz/buffers-windows-tabs/.

I know this plugin will allow window navigation, between vim splits (or windows... or panes) and tmux panes. However since I have this mappings I have a conflict:

```vimscript
map <C-h> :bprevious<Cr>
map <C-l> :bnext<Cr>
map <C-k> :tabprevious<Cr>
map <C-j> :tabnext<Cr>
```

That is why I was asking to use `<C-w> hjkl` as the mappings, but as you pointed out word deletion is affected.

So I was just wondering... _if @christoomey uses `<C-hjkl>` for jumping between windows/splits in vim and tmux, what mappings does he use for navigating buffers?_ You don't have to tell if you don't want to, but I was just curious to know, and see if it was a good idea and then if I liked it then change my mappings also to use this plugin without issues.

However you can close the issue now, I think tmux is not for me

**Comment by christoomey** [comment]
Hi @ZzAntares, thank you for clarifying. I think I've finally caught up to what you are talking about. I think the reason I had difficulty understanding was that I almost never use the buffer cycling / hidden buffer functionality in Vim. I honestly can't remember the last time I used `:bnext` or similar. Instead, I use windows and tabs.

All that said, to finally answer your original question, I have no mappings for navigating buffers as I almost never do it. 

That said, I see no reason that you couldn't find a set of mappings for navigation and another set for buffer cycling. The question is just which is more common for you. If the buffer cycling is more common, then I think setting that to `C-h`, `C-j`, etc is just fine. Likewise, while not ideal, I think the `C-w` prefix could work fine, knowing that you would want to configure and get used to `C-w C-w` for killing a word. (For the record, I use `C-s` as my tmux prefix).

I'm going to close this issue now as I don't think there is anything specific to `vim-tmux-navigator` here, but please feel free to comment or reopen if you have additional questions or think there is something specific to the plugin.

**Comment by ZzAntares** [comment]
Thanks!
