### ISSUE TITLE
Use process list to determine if Vim is active

### ISSUE THREAD

**Issue by christoomey** [christoomey/vim-tmux-navigator#96]
Currently we use a check of tmux's `pane_current_command` to determine if Vim is active. This has worked _just_ well enough, but is prone to a number of edge cases and false negatives.

Instead, I want to look into another approach that would examine the process tree for the pane, and detect Vim that way.

Via tmux's `{pane_pid}` format option to the `display-message` command we can get the parent pid of the pane. From there, we can use `pstree` to get the child process tree of the pane. The check is then if the current process (last element in `pstree` listing) is Vim.

A rough, half-working version of this is:

``` sh
ps -p $(tmux display-message -p -t 0 -F '#{pane_pid}' | xargs pstree | tail -1 | cut -d ' ' -f 3) -o comm=
```

That outputs `/usr/local/Cellar/macvim/7.4-73_1/MacVim.app/Contents/MacOS/Vim` in my case, which could be matched agains for Vim checking

Lost to improve here (is `pstree` available?, better `sed` for getting the leaf pid, etc), but it's a start I think

**Comment by patrickdepinguin** [comment]
On my Linux system, the pstree output is separated with 3 dashes, for example:

    echo 4604 | xargs pstree 
    bash───xargs───vim

To get to vim, you can use the following command:

    echo 4604 | xargs pstree | tail -1 | rev | cut -d- -f1 | rev

The first echo would obviously need to be replaced.
Alternatively, since we're only interested in the last few characters being 'vim' (or derivative) or not, we could simply search for that string at the end, e.g.

    echo 4604 | xargs pstree | grep 'vim$'

**Comment by blueyed** [comment]
> we could simply search for that string at the end

That won't work with nvim, which might have python subprocesses, and even childs inside (via `:terminal`):

  |   `-zsh,28494
  |       `-nvim,29542
  |           |-python3,29547 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() script_host.py
  |           |-python3,29558 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/user/.vim/neobundles/deoplete/rplugin/python3/deoplete
  |           |-zsh,29577 -i
  |           |   `-nvim,29729
  |           |       |-pstree,29752 -apl
  |           |       |-python3,29734 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() script_host.py
  |           |       |-python3,29735 -c import sys; sys.path.remove(""); import neovim; neovim.start_host() /home/user/.vim/neobundles/deoplete/rplugin/python3/deoplete
  |           |       `-{nvim},29732
  |           `-{nvim},29545

Using `pgrep -s` will only select the main session (28494,29542,29547,29558).

See https://github.com/christoomey/vim-tmux-navigator/pull/117 for an implementation.

**Comment by sergei-dyshel** [comment]
I have a similar problem to the one described here. I run *vim* with some wrapper written in *bash*, so `pane_current_command` always returns `bash`.

The most reliable solution I found is to look by *tty*, for that I've changed `is_vim` definition to:
```bash
is_vim='ps -o cmd -t "#{pane_tty}" | grep -iqE "(^|\/)g?(view|n?vim?x?)(diff)? "'
```
 What it does is search for all processes bound to *tty* returned by `#{pane_tty}` and check if one of them matches *vim* regex.

**Comment by blueyed** [comment]
@sergei-dyshel 
Have you tried / looked at #117?

**Comment by sergei-dyshel** [comment]
@blueyed 
Nope, missed it somehow :smile:. Good work!
