### ISSUE TITLE
Sending literal C-k

### ISSUE THREAD

**Issue by marcaddeo** [christoomey/vim-tmux-navigator#99]
How does one send a literal C-[k/j/k/l]?

**Comment by christoomey** [comment]
Hey @marcaddeo, check out the [Restoring Clear Screen (C-l)](https://github.com/christoomey/vim-tmux-navigator#restoring-clear-screen-c-l) section in the readme. It is specific to `C-l` but the same technique should apply to the other keys as well.

I'm going to close this issue now as I think the provided link should cover your question, but please feel free to comment or reopen if you hit any issues.
